Install: Show/Hide admin password during install #3431 - GH#3431
chamilo/chamilo-lms pull request #3432
Opened 2020-08-05 20:52 UTC by carlangas159

![image](https://user-images.githubusercontent.com/18097392/89462666-6372e700-d733-11ea-9bdd-0ba647af7bdc.png)

I try to made by display_configuration_parameter but havent possibility to add elements into div

2020-11-12 21:02 UTC, ywarnier requested changes

2020-11-12 21:02 UTC, ywarnier commented on public/main/install/index.php
> +        ShowHidePassword()
Esta llamada usa una mayúscula al inicio del nombre de la función, pero la función está declarada sin mayúscula.

2020-11-12 21:02 UTC, ywarnier commented on public/main/install/index.php
> +</script>
Por lo general no estoy seguro de porqué el código está tan distinto para master que lo que hay en 1.11.x: https://github.com/chamilo/chamilo-lms/blob/f14ba11afb7d7e36abdc788674069509de7b64d4/main/install/index.php#L971-L982

2020-11-17 17:02 UTC, carlangas159 commented on public/main/install/index.php
> +        ShowHidePassword()
La he acomodado a mayuscula. Muchas gracias por notificarlo

2020-11-17 17:03 UTC, carlangas159 commented on public/main/install/index.php
> +</script>
Puede ser por la renovacion del sistema, es diferente el codigo por la implementacion de Vue. En principio se trato de ajustar el mismo codigo de 1.11 para 2, pero hay diferencias y lo estableci por una funcion.

2021-02-17 18:13 UTC, carlangas159 commented
Updated:

Show/hide admin password on installation like chamilo 1.11.x and code update.

> ![image](https://user-images.githubusercontent.com/18097392/108246397-62c5ff00-711f-11eb-8b1c-46d2fd93010e.png)
> ![image](https://user-images.githubusercontent.com/18097392/108246440-6f4a5780-711f-11eb-8ea3-c16aeeb9f5e6.png)

2023-03-20 18:34 UTC, AngelFQC commented
This was fixed here https://github.com/chamilo/chamilo-lms/commit/1b2ceeb174103205f75a1709f343527ed208d2f4#diff-88fcc4c8c6559ba91d00fc7ce06d588cf9a1989b60868fc10e41365beb1d4f1eR75-R82

2023-03-20 18:34 UTC, closed without merging