WIP: System: Modifying entity with annotations for user_id. the previous one is commented
chamilo/chamilo-lms pull request #3464
Opened 2020-08-20 22:48 UTC by carlangas159

All found user_ids have been changed to conform to annotated doctrine. The previous elements remain commented for security - refs #3463

2020-08-21 07:12 UTC, jmontoyaa requested changes

2020-08-21 07:12 UTC, jmontoyaa commented on src/CoreBundle/Entity/GradebookEvaluation.php
> +     *      inversedBy="gradebook_evaluation")
Aqui sería un ManyToOne.
Usar gradebookEvaluations como inversedBy

2020-08-21 07:12 UTC, jmontoyaa commented on src/CoreBundle/Entity/GradebookLink.php
> +     * @ORM\OneToOne (targetEntity="Chamilo\CoreBundle\Entity\User",
Usar ManyToOne

2020-08-21 07:12 UTC, jmontoyaa commented on src/CoreBundle/Entity/GradebookResult.php
> +     * @ORM\OneToOne (targetEntity="Chamilo\CoreBundle\Entity\User",
Usar ManyToOne

2020-08-21 07:12 UTC, jmontoyaa commented on src/CoreBundle/Entity/GradebookResultLog.php
> +     * @ORM\OneToOne (targetEntity="Chamilo\CoreBundle\Entity\User",
Usar ManyToOne, si se usa OneToOne entonces doctrine genera un unique para ese user_id
Revisar para todos los casos esa relación y también el formato de inversedBy (camelcase) y tambien su presencia en User.php

2020-09-01 22:35 UTC, AngelFQC commented on src/CoreBundle/Entity/UserRelUser.php
> +     *      inversedBy="user_rel_user")
`user_rel_user` is incorrect for `inversedBy`. Because it should be the class property in User entity.

2020-09-01 22:36 UTC, AngelFQC commented on src/CoreBundle/Entity/UserRelTag.php
> +     *      inversedBy="user_rel_tag")
`user_rel_tag` is incorrect for `inversedBy`. Because it should be the class property in User entity.

2020-09-01 22:36 UTC, AngelFQC commented on src/CoreBundle/Entity/UserRelCourseVote.php
> +     *      inversedBy="user_rel_course_vote")
`user_rel_course_vote` is incorrect for `inversedBy`. Because it should be the class property in User entity.

2020-09-02 06:32 UTC, jmontoyaa commented
@carlangas159  Algun update de este PR?

2020-09-02 20:45 UTC, carlangas159 commented on src/CoreBundle/Entity/ClassUser.php
> -     * @var int
La he marcado como deprecated

2020-09-02 20:51 UTC, carlangas159 commented
He colocado algunas relaciones en las entidades, corrijanme si me equivoco por favor

$admin   -> 1 admin / 1 user

$gradebookCertificate   -> n gradebookCertificate / 1 user
$gradebookEvaluation   -> b gradebookEvaluation / 1 user
$gradebookLink   -> n gradebookLink / 1 user
$gradebookResult   -> n gradebookResult / 1 user
$gradebookResultLog   -> n gradebookResultLog / 1  user
$gradebookScoreLog   -> n gradebookScoreLog / 1 user
$sequenceValue   -> n sequenceValue / 1 user
$trackEAttemp   -> n trackEAttemp / 1 user
$trackECourseAccessRepository   -> n trackECourseAccessRepository / 1 user
$userCourseCategory   -> n userCourseCategory / n1 user
$userRelCourseVote   -> n userRelCourseVote / 1 user
$userRelTag   -> n userRelTag / 1 user
$userRelUser   -> n userRelUser / 1 user


$templates   -> n templates / 1 user   - tengo dudas sobre este


He colocado la asociación de inversedBy en user respectivamente como lo especifica angel (muchisimas gracias), sin embargo, no estoy seguro si estas relaciones de 1 a muchos esten totalmente correctas.

2020-09-07 14:25 UTC, jmontoyaa commented
Aún no agregar api platform este PR es solo de las entidades de usuario.

2020-09-07 14:34 UTC, jmontoyaa commented on src/CoreBundle/Entity/Admin.php
>      protected $userId;
Eliminar el $userId, pues ya está declarado en "protected $user;"

2020-09-07 14:34 UTC, jmontoyaa commented on src/CoreBundle/Entity/Admin.php
>      public function setUserId($userId)
Eliminar setUserId, getUserId

2020-09-07 14:34 UTC, jmontoyaa commented on src/CoreBundle/Entity/GradebookCertificate.php
> +     * @deprecated  Use setUser
Para todos los casos eliminar los setUserId y getUserId

2020-09-07 14:34 UTC, jmontoyaa commented on src/CoreBundle/Entity/GradebookCertificate.php
> +     * @return User
No es necesario agregar "@return User", pues ya se usa el type hint User

2020-09-07 14:34 UTC, jmontoyaa commented on src/CoreBundle/Entity/SequenceValue.php
> +     * @ORM\Column(name="user_id", type="integer", nullable=false)
Eliminar  protected $userId;

2020-09-07 14:34 UTC, jmontoyaa commented on src/CoreBundle/Entity/TrackEAttempt.php
> -     * @ORM\ManyToOne(targetEntity="Chamilo\CoreBundle\Entity\Course", inversedBy="trackEAttempts")
Porque cambiarlo a singular? Un curso puede tener muchos intentos.

2020-09-07 14:34 UTC, jmontoyaa commented on src/CoreBundle/Entity/User.php
> +    protected $gradebookCertificate;
Como es un oneToMany tiene que estar en plural $gradebookCertificates, lo mismo para el resto de casos.

2020-09-07 14:34 UTC, jmontoyaa commented on src/CoreBundle/Entity/User.php
> +        $this->gradebookCertificate = $gradebookCertificate;
Cuidado con el formato de código, dar un nuevo espacio en el return.
No es necesario poner el @ param ni el @ return pues la función ya está con type hint.

2020-09-07 15:45 UTC, carlangas159 commented on src/CoreBundle/Entity/TrackEAttempt.php
> -     * @ORM\ManyToOne(targetEntity="Chamilo\CoreBundle\Entity\Course", inversedBy="trackEAttempts")
No se tocaria los cursos en este pr, me parece que https://github.com/chamilo/chamilo-lms/pull/3466 esta mas en relacion a cursos

2020-09-07 16:58 UTC, carlangas159 commented on src/CoreBundle/Entity/GradebookCertificate.php
> +     * @deprecated  Use setUser
Eliminados en 
Admin.php
ClassUser.php
GradebookCertificate.php
GradebookEvaluation.php
GradebookLink.php
GradebookLinkevalLog.php
GradebookResult.php
GradebookResultLog.php
GradebookScoreLog.php
SequenceValue.php
Templates.php
TrackEAccessComplete.php
TrackEAttempt.php
TrackECourseAccess.php
TrackEExerciseConfirmation.php
User.php
UserCourseCategory.php
UserRelCourseVote.php
UserRelTag.php
UserRelUser.php

2020-09-07 16:59 UTC, carlangas159 commented on src/CoreBundle/Entity/User.php
> +    protected $gradebookCertificate;
Se ajusto en plural las variables de User.php: 

> $gradebookCertificates
> $gradebookEvaluations
> $gradebookLinks
> $gradebookResults
> $gradebookResultLogs
> $gradebookScoreLogs
> $sequenceValues
> $trackEExerciseConfirmations
> $templates
> $trackEAttemps
> $trackECourseAccess
> $userCourseCategorys
> $userRelCourseVotes
> $userRelTags
> $gradebookLinkevalLogs
> $userRelationships

2020-09-08 06:13 UTC, jmontoyaa commented on src/CoreBundle/Entity/TrackEAttempt.php
> -     * @ORM\ManyToOne(targetEntity="Chamilo\CoreBundle\Entity\Course", inversedBy="trackEAttempts")
Pero se está cambiando trackEAttempts a trackEAttempt. Dejarlo como antes.

2020-09-08 16:28 UTC, carlangas159 commented
Se han añadido los elementos de CourseBundle que tienen user_id.
Se ha ajustado los modelos para que api platform pueda cargarlos, por eso he añadido el siguiente bloque en el comentario de la clase en aquellas que no tenían dicha documentación

>   @ApiResource(
>        attributes={"security"="is_granted('ROLE_ADMIN')"},
>        iri="",
>        normalizationContext={"groups"={"user:read"}},
>        denormalizationContext={"groups"={"user:write"}},
>        collectionOperations={"get"},
>        itemOperations={"get"}
>    )

Para prevenir cualquier modificación actual por api, solo he dejado el metodo get asi se podria ir ajustando conforme se requiera.

También el las propiedades se ha añadido, según la documentación para apiplatform, el tipo y la propiedad, esto para que pueda ajustarse la documentación fácilmente.

>  @var User
> @ApiProperty(iri="http://schema.org/Person")

También aplica para su contraparte en user.php

2020-09-09 06:17 UTC, jmontoyaa commented
Como repito, favor de remover apiplatorm de este PR y efectuar los cambios solicitados solo para el tema de user id y doctrine.

No se ha solicitado implementar api platform todavía en todas la entidades.

2020-09-09 14:18 UTC, jmontoyaa commented
Corregir lo que indica flint https://flintci.io/repositories/1013/analyses/42481

Una vez que flint valide el código revisar lo que indica el action PHP Composer / PHP 7.3

2020-09-11 08:01 UTC, jmontoyaa commented
Sería una buena idea de usar traits en lugar de re escribir getUser y setUser, el trait puede ser creado aquí:

/srv/http/chamilo2/src/CoreBundle/Traits/UserTrait.php

Ya existe un trait para los cursos por si acaso:

/srv/http/chamilo2/src/CoreBundle/Traits/CourseTrait.php

2020-09-11 10:16 UTC, jmontoyaa commented
Revisar que las funciones eliminadas sean reemplazadas:

Ejemplo:

Antes:

```
$userId = $obj->getUserId();

```

Después:

```
$userId = $obj->getUser()->getId();
```

2020-09-23 21:53 UTC, carlangas159 commented
Se han cambiado los setUser y getUser por la implementación de trait. sin embargo, no he podido evaluar aún setUser y getUser en código legacy, ya que debo generar el escenario para cada parte y poder probarlo 


![image](https://user-images.githubusercontent.com/18097392/94072987-5336ca00-fdbc-11ea-8aeb-dd0934873c68.png)

El cual afectaría para el momento de su ejecución.

![image](https://user-images.githubusercontent.com/18097392/94073341-f091fe00-fdbc-11ea-96b4-979bf4f1568a.png)

He tratado de generar un escenario para quiz, añadiendo una pregunta a un ejercicio en un curso y me salio este aviso 
![image](https://user-images.githubusercontent.com/18097392/94073486-2df68b80-fdbd-11ea-8c48-46b4bd0ce508.png)

Por lo momento, la verificación de remover setUserId para setUser tomará tiempo para poder evaluar cada elemento en legacy

2020-09-25 09:48 UTC, jmontoyaa requested changes

2020-09-25 09:48 UTC, jmontoyaa commented on public/main/gradebook/lib/be/abstractlink.class.php
> +    public function getUser()
Eliminar esta función. Usar: 

`api_get_user_entity($userId);`

2020-09-25 09:48 UTC, jmontoyaa commented on public/main/exercise/exercise.class.php
> +                $em = Database::getManager();
Usar:

`api_get_user_entity($userId);`

2020-09-25 09:48 UTC, jmontoyaa commented on public/main/forum/forumfunction.inc.php
> +    $em = Database::getManager();
Lo mismo para todos los cambios. api_get_user_entity($userId);

2020-09-25 09:48 UTC, jmontoyaa commented on public/main/gradebook/lib/be/evaluation.class.php
> +     * @return User|object|null
Eliminar función

2020-09-25 09:48 UTC, jmontoyaa commented on src/CoreBundle/Entity/GradebookCertificate.php
> +     * @ORM\ManyToOne (
Eliminar espacio en blanco, lo mismo en todos los otros casos.

` @ORM\ManyToOne(`

2020-09-25 09:48 UTC, jmontoyaa commented on src/CoreBundle/Entity/TrackEAttempt.php
> +use ApiPlatform\Core\Annotation\ApiProperty;
Eliminar clase

2020-09-25 09:48 UTC, jmontoyaa commented on src/CoreBundle/Entity/User.php
> +    protected $userCourseCategorys;
protected $userCourseCategories

2020-09-25 09:48 UTC, jmontoyaa commented on src/CoreBundle/Entity/User.php
> +    protected $cAttendanceResults;
Usar $attendanceResults

2020-09-25 09:48 UTC, jmontoyaa commented on src/CoreBundle/Entity/User.php
> +    protected $cAttendanceSheets;
attendanceSheets

2020-09-25 09:48 UTC, jmontoyaa commented on src/CoreBundle/Entity/User.php
> +    protected $cBlogRatings;
Usar blogRatings, lo mismo para el resto de propiedades

2020-09-25 09:48 UTC, jmontoyaa commented on src/CoreBundle/Entity/User.php
> +    protected $cDropboxCategorys;
$dropboxCategories corregir todas las llamadas, lo mismo para los otros casos similares

2020-09-25 09:50 UTC, jmontoyaa commented
Solamente cambiar las llamadas $userId = $obj->getUserId(); por lo nuevo, los ejercicios aún no funcionan en v2 y hay muchas cosas por corregir aún.

2020-09-25 17:26 UTC, carlangas159 commented on src/CoreBundle/Entity/User.php
> +    protected $userCourseCategorys;
en src/CoreBundle/Entity/TrackEAttempt.php no se podría eliminar ya que depende por cursos 

 /**
     * @var Course
     * @ApiProperty(iri="http://schema.org/Course")  <<<<
     * @ORM\ManyToOne(
     *     targetEntity="Chamilo\CoreBundle\Entity\Course",
     *     inversedBy="trackEAttempts"
     * )

2020-09-28 06:49 UTC, jmontoyaa commented
Voy ha agregar estos cambios parcialmente a master

2020-09-28 09:52 UTC, jmontoyaa commented
He agregado los cambios hechos en src/CoreBundle.
Los cambios hechos a src/CourseBundle no serán pasados, pues esas entidades van ha hacer resources y los resources tienen datos del autor en resourceNode.creator

2020-09-30 08:14 UTC, closed without merging