API para obtener información de tareas e información de entregas por parte de estudiantes
chamilo/chamilo-lms pull request #3513
Opened 2020-09-11 19:06 UTC by UriReyes

Se agregó API para obtener las tareas enviadas por el docente, así como para obtener información de las entregas realizadas por los estudiantes

2020-09-12 22:19 UTC, ywarnier commented on public/main/inc/lib/webservices/Rest.php
> +                    $url="https://".$_SERVER['SERVER_NAME']."/main/work/work_list.php?cidReq=$course_code&id_session=0&gidReq=0&gradebook=0&origin=&id=$id";
Please use api_get_path(WEB_CODE_PATH) to obtain the equivalent of "http://$_SERVER['SERVER_NAME']/main/"

2020-09-12 22:20 UTC, ywarnier commented on public/main/inc/lib/webservices/Rest.php
> +     /**
Please add a line of description about what the method is supposed to do

2020-09-12 22:21 UTC, ywarnier commented on public/main/inc/lib/webservices/Rest.php
> +    public function getHomework($course_id){
Please use only camelCase variable names for new code. lowercase with _ is only for legacy code.

2020-09-12 22:21 UTC, ywarnier commented on public/main/inc/lib/webservices/Rest.php
> +        $workassignment =Database::get_course_table(TABLE_STUDENT_PUBLICATION_ASSIGNMENT);
Camel case and "Table" suffix, to maintain consistency ($workAssignmentTable)

2020-09-12 22:22 UTC, ywarnier commented on public/main/inc/lib/webservices/Rest.php
> +                while($row= Database::fetch_array($result, 'ASSOC')){
A lot of spacing issues that do not conform to our [[Coding conventions]]

2020-09-12 22:25 UTC, ywarnier commented on public/main/inc/lib/webservices/Rest.php
> +    private function getCourseCode($course_id)
There's no need to re-implement this methos (api_get_course_info_by_id($course_id) would give you an array with a 'code')

2020-09-12 22:28 UTC, ywarnier commented
@UriReyes gracias por tu contribución. Hice una serie de comentarios en una primera revisión *muy* rápida. Por lo visto no conoces nuestras conversiones de código. Si usas un IDE moderno, te recomiendo activar el soporte de PSR-2, que te ayudará a tenerlo auto-mejorado. En todo caso, usamos y respetamos PSR-1 y PSR-2 como convenciones.
También respetamos tu tiempo, y si nos dices que no vas a poder revisarlo, está bien, adaptaremos tu PR nosotros pero puede que demore más en ser aceptado.

2020-09-14 04:54 UTC, AngelFQC requested changes
There are methods to get the assigments in course (or session) and get info about one assigment in `main/work/work.lib.php`.

Please check them to avoid duplicating functions that do the same.

2020-09-14 04:54 UTC, AngelFQC commented on public/main/webservices/api/v2.php
> +            $idCourse=$_REQUEST['c_id'];
Don't use `$_REQUEST['c_id']`. The request param to use is `course` and it's set in line 33, like with session.

Please, check `Rest::getCourseDocuments` for reference.

2020-09-14 04:54 UTC, AngelFQC commented on public/main/webservices/api/v2.php
> +            $idCourse=$_REQUEST['c_id'];
Don't use `$_REQUEST['c_id']`.

2020-11-12 21:16 UTC, ywarnier commented
Hola @UriReyes 
Este mensaje para saber si tienes intención de atender las observaciones que te dejamos 2 meses atrás, o si lo dejas ahí y nunca lo podrás atender (cosa que podamos planificar si lo incluimos o no).

2023-02-03 15:35 UTC, ywarnier commented
Will not integrate this PR "as is" because it lacks minimum quality standards required for Chamilo and the author did not answer in more than 2 years

2023-02-03 15:35 UTC, closed without merging