Ticket: Add extra data, learningpath_id and exercise id
chamilo/chamilo-lms pull request #3564
Opened 2020-10-15 21:01 UTC by lcubas

2020-10-16 22:53 UTC, AngelFQC requested changes

2020-10-16 22:53 UTC, AngelFQC commented on main/inc/lib/TicketManager.php
> +                        $urlParamsExercise .= '&exerciseId='.$row['exercise_id'];
Se puede usar [http_build_query](https://php.net/http_build_query)

2020-10-16 22:53 UTC, AngelFQC commented on main/inc/lib/exercise.lib.php
> +    public static function getExerciseById($exerciseId)
`getExerciseById` indica que se va a obtener todo el quiz, pero sólo retorna el título.

En casi de sólo retornar un valor, en un query DQL se puede usar `getSingleScalarResult()`

2020-10-16 22:53 UTC, AngelFQC commented on main/inc/lib/TicketManager.php
> +            'message' => $content
Aquí sí va la coma al final :)

2020-10-16 22:53 UTC, AngelFQC commented on main/install/configuration.dist.php
> +
Normalmente los cambios de DB deben ir con una nueva variable de configuración desactivada, tipo `$_configuration['ticket_add_quiz_lp'] = false;` (no necesariamente esa), que la funciona la nueva funcionalidad se habilite con esta configuración.

2020-10-16 22:53 UTC, AngelFQC commented on main/lp/learnpath.class.php
> +            ->getArrayResult();
Algo parecido con la función `getExerciseById`

2020-10-16 22:53 UTC, AngelFQC commented on main/install/configuration.dist.php
> +
De esta forma la funcionalidad de tickets puede funcionar como está ahora, sin tener que modificar la DB.

2020-10-25 19:39 UTC, kemoche commented
Adding to the above Add extra data - I wish on the Learners reporting list (Administrator ->Reporting -> Learners), to have two additional field when exporting/downloading to excel to minimize confusion with learners with two similar names
When 2 or more learning have similar names it creates confusion and time wasting to differentiate. I would wish the OfficialCode (Code) & PhoneNumber (Phone) were included in this report printing to minimize the confusion.
See attached...
If its possible to share the changes on ../chamilo/main/mySpace/student.php would appreciate.
Cheers

2020-11-12 22:58 UTC, ywarnier requested changes
Cambios por aplicar

2020-11-12 22:58 UTC, ywarnier commented on main/inc/ajax/exercise.ajax.php
> +        $course_id = (isset($_GET['course_id']) && !empty($_GET['course_id'])) ? $_GET['course_id'] : 0;
Se supone que $course_id será un entero (por la llamada a get_all_exercises_for_course_id() a continuación), por lo que $course_id *debe* ser un (int) de $_GET['course_id'] (debe tener un mínimo de filtrado en la base, además que si vas más allá verás que get_all_exercises_for_course_id() no lo filtra).

2020-11-12 22:58 UTC, ywarnier commented on main/inc/ajax/lp.ajax.php
> +        $course_id = (isset($_GET['course_id']) && !empty($_GET['course_id'])) ? $_GET['course_id'] : 0;
Mismo filtrado (int) aquí, por la misma razón.

2020-11-12 22:58 UTC, ywarnier commented on main/install/configuration.dist.php
> +
@lcubas, yo apoyo este comentario de @AngelFQC y veo que lo hiciste, pero es necesario renombrar la variable en `$_configuration['ticket_lp_quiz_info_add'] = false;`.
Pon esta línea de $_configuration *después* de los 4 ALTER TABLE (es más claro así para evidenciar que los queries deben ser ejecutados antes)

2020-11-12 22:58 UTC, ywarnier commented on main/ticket/ticket_details.php
> +    if (api_get_configuration_value('ticket_add_quiz_and_lp')) {
Renombrar esta según el comentario arriba.

2020-11-12 22:58 UTC, ywarnier commented on main/ticket/tickets.php
> +            $extraParams .= '&exerciseId=' . $_GET['exerciseId'];
OK, eso *no puede* estar así sin filtrado. *tienes* que usar un (int)

2020-11-12 22:58 UTC, ywarnier commented on main/ticket/tickets.php
> +            $extraParams .= '&lpId=' . $_GET['lpId'];
No *puede* estar así sin filtrado. tienes que usar un (int)

2020-11-17 14:04 UTC, NicoDucou commented
Probe la funcionalidad y todo ok funciona correctamente.

2020-11-17 17:25 UTC, ywarnier requested changes
Falta una revisión más

2020-11-17 17:25 UTC, ywarnier commented on main/ticket/ticket_details.php
> +    if (api_get_configuration_value('ticket_lp_quiz_info_add')) {
Aquí falta renombrar la variable. Ojo con esto. Los pequeños detalles rinden un sistema inestable.

2020-11-17 17:25 UTC, ywarnier commented on main/ticket/tickets.php
> +            $extraParams .= '&exerciseId=' . intval($_GET['exerciseId']);
Preferimos la fórmula `(int) $_GET['exerciseId']` a la de `intval($_GET['exerciseId'])`

2020-11-17 17:25 UTC, ywarnier commented on main/ticket/tickets.php
> +            $extraParams .= '&lpId=' . intval($_GET['lpId']);
(int)

2020-11-17 17:25 UTC, ywarnier commented on main/inc/ajax/exercise.ajax.php
> +        $course_id = (isset($_GET['course_id']) && !empty($_GET['course_id'])) ? intval($_GET['course_id']) : 0;
(int)

2020-11-17 17:25 UTC, ywarnier commented on main/inc/ajax/exercise.ajax.php
> +        $session_id = (!empty($_GET['session_id'])) ? intval($_GET['session_id']) : 0;
(int)

2020-11-17 17:25 UTC, ywarnier commented on main/inc/ajax/lp.ajax.php
> +        $results = learnpath::getLpList($course_id, $onlyActiveLp);
Me sorprende que no haya un parametro $sessionId aquí... pero veo que getLpList() no lo tiene. Se podría hacer esta mejora en otro PR

2020-11-17 17:25 UTC, ywarnier commented on main/inc/ajax/lp.ajax.php
> +        $course_id = (isset($_GET['course_id']) && !empty($_GET['course_id'])) ? intval($_GET['course_id']) : 0;
(int)

2020-11-17 17:25 UTC, ywarnier commented on main/install/configuration.dist.php
> +// - Require change DB
Required DB change

2020-11-17 22:35 UTC, merged