Session: prevents a user with an active session from accessing the courses
chamilo/chamilo-lms pull request #3567
Opened 2020-10-16 18:15 UTC by carlangas159

When a user is deactivated when they already have a session open, they can continue with their normal performance until the moment their session expires.

A validation is made in api_protect_course_script for when the user_id of the session is different from 0, it is checked in the database that this active to access the course.

2020-10-16 18:21 UTC, carlangas159 commented
@AngelFQC

2020-10-16 21:04 UTC, AngelFQC requested changes
Podría funcionar, pero sólo en las páginas que estén dentro de un contexto de curso. Si se desactiva el usuario y este está en una herramienta fuera del curso, podría seguir con su sesión.

2020-10-16 21:04 UTC, AngelFQC commented on main/inc/lib/api.lib.php
> +            WHERE id = $user_id";
Falta escapar el $userId o castearlo a entero.

2020-10-16 21:04 UTC, AngelFQC commented on main/inc/lib/api.lib.php
> +        api_not_allowed(true, get_lang('AccountInactive'));
Agregar `Display::return_message` de tipo 'error'.

2020-10-17 15:05 UTC, ywarnier commented
Estaba revisando esto...
Lo de hacer el checkeo solo en páginas específicas de cursos o de admin es una media-medida.
Porqué no poner una opción de configuración en configuration.dist.php tipo:
```
// Add another layer of security by checking if the user is disabled at every page load (might generate considerable extra DB load)
// $_configuration['security_block_inactive_users_immediately'] = false;
```
Y de ahí modificar local.inc.php para ver si `api_get_configuration_setting('security_block_inactive_users_immediately')` y entonces (solo en este caso) añadir el check de apiBlockInactiveUser(). Esto tendría efecto global inmediato, a cambio de un peso mayor sobre la base de datos (justificado si queremos una seguridad superior).

No?

2020-10-17 22:37 UTC, carlangas159 commented
Estoy de acuerdo, actualmente solo se ha colocado en una sola función para la página del curso, pero si se quiere un aspecto global se coloca como variable en config y se puede llegar a separar la función, dentro de la misma obtener la configuración, obtener el ID del usuario actual y restringirle el acceso a casi cualquier ámbito. ApiBlockCurrentUserInactive pudiese llamarse la función

2020-10-19 16:11 UTC, carlangas159 commented
Se agrega security_block_inactive_users_immediately en  configuration.dist.php. Para activar la verificacion en base de datos para que no impacte en el rendimiento.

Se agrega la funcion apiBlockInactiveUser  en :

- api_protect_course_script = Bloquea las paginas de curso.
- api_protect_admin_script = Bloquea las paginas administrativas.
- api_protect_anonymous_users = Bloquea en las paginas anonimas. Aplica para el usuario anonimo del sistema.
- Pagina de perfil del usuario 
- Pagina de quien esta en linea.
- Pagina de Agenda
- Pagina de mis certificados. 

api_get_user_id debe devolver el numero del usuario, si este es 0 (o no se encuentra) no aplica.

2020-11-12 23:08 UTC, ywarnier requested changes
2 pequeños cambios menores por hacer antes del merge

2020-11-12 23:08 UTC, ywarnier commented on main/inc/lib/api.lib.php
> +    if( api_get_configuration_value('security_block_inactive_users_immediately') != 1){
pequeño error de espacios aquí (al inicio y el fin de la línea)

2020-11-12 23:08 UTC, ywarnier commented on main/install/configuration.dist.php
> +// $_configuration['security_block_inactive_users_immediately'] = false;
Como dice en la línea 1684, hay que dejar esta última sección al final, así que estas dos nuevas líneas deberían encontrarse en la línea 1684 (antes del "KEEP...")

2020-11-13 16:55 UTC, carlangas159 commented on main/install/configuration.dist.php
> +// $_configuration['security_block_inactive_users_immediately'] = false;
Lo he movido para que este donde indicas

2020-11-13 16:55 UTC, carlangas159 commented on main/inc/lib/api.lib.php
> +    if( api_get_configuration_value('security_block_inactive_users_immediately') != 1){
le he aplicado el flici

2020-11-13 18:40 UTC, carlangas159 commented on main/inc/lib/api.lib.php
> +            WHERE id = $user_id";
Fue cambiado por :
$userId = api_get_user_id();

2020-11-17 22:56 UTC, ywarnier commented on main/inc/lib/api.lib.php
> +    if (api_get_configuration_value('security_block_inactive_users_immediately') != 1) {
Lo voy a cambiar yo para ir más rápido, pero aquí puedes optimizar la eficiencia para 99% de los casos (en que este parámetro *no está* activo, pasando este bloque *antes* de api_get_user_id() y api_get_path(), que pueden ser algo pesadas.

2020-11-17 22:57 UTC, ywarnier commented on main/inc/lib/api.lib.php
> + * @param int $user_id
Técnicamente la función no toma ningún $user_id, por lo que esta documentación es incorrecta.

2020-11-17 22:58 UTC, ywarnier commented on main/inc/lib/api.lib.php
> + * @return bool
debería tener una descripción más amplia. Por ejemplo: `@return bool True if user is active (and it NOT blocked), false if the user is blocked.

2020-11-17 22:59 UTC, ywarnier commented on main/auth/profile.php
> +// see BT#17891
Este comentario no es necesario. Se puede encontrar por el historial Git y BT no está disponible para el público.

2020-11-17 23:01 UTC, merged