Display: Ajuste de mensajes antes que texto de introduccion
chamilo/chamilo-lms pull request #3585
Opened 2020-10-26 18:35 UTC by carlangas159

Cuando se intenta recuperar la contraseña y el sitio tiene habilitado un texto de introduccion, los avisos saldran luego de este en el layout de 1 columna,

> ![total](https://user-images.githubusercontent.com/18097392/97213563-c2268a80-178f-11eb-8614-b40f8bb1dc19.png)

Se añade una variable en el layout para poder asignarla y limpiar las variables previniendo la duplicacion del mensaje, similar a la siguiente imagen 

> ![EjemploAviso](https://user-images.githubusercontent.com/18097392/97213640-e2eee000-178f-11eb-8771-9fda4965db1b.PNG)

De este modo, solo se le asignaria el contenido a flashMessagesOnTop  para mostrarse uno solo

> ![Screenshot_2020-10-26 Beeznest - Campus Linux(1)](https://user-images.githubusercontent.com/18097392/97213725-fef28180-178f-11eb-9759-262e7c4246d2.png)

 BT#17931

2020-11-03 18:28 UTC, AngelFQC requested changes

2020-11-03 18:28 UTC, AngelFQC commented on index.php
> +$controller->tpl->display_two_col_template(true);
`Template::display_two_col_template` no recibe parámetros y en el PR no se modifica la función

2020-11-04 09:38 UTC, jmontoyaa commented
No creo que sea una buena idea de agregar otra variable para mensajes flash.
Ya tenemos Display::addFlash(); que maneja todo ese proceso. Lo mejor sería modificar el texto de introducción para que aparezca abajo.

2020-11-04 14:50 UTC, carlangas159 commented
Hola @jmontoyaa , se trata de la modificacion de la plantilla, no se si afecte otros modulos, por eso he generado otra variable donde se le asigna el valor del flash (flashMessagesOnTop) y borra el otro elemento , esta variable si esta arriba del mensaje inicial pero solo en la plantilla main/template/default/layout/layout_2_col.tpl ya que esta plantilla usa otra (layout/page_body.tpl) donde se encuentra el aviso de mensajes pero tambien el cuerpo de la pagina, no seria conveniente modificar la plantilla para determinar que modulos se afectan si se ajusta el mensaje

2020-11-18 00:02 UTC, ywarnier commented
En base al comentario de @jmontoyaa sobre mover el elemento del TPL flash_messages (que aparece en page_body.tpl que está cargado desde layout_2_col.tpl).
Ocurre que la sección que aparece antes del mensaje Flash es la sección que muestra la variable home_include, y esta variable podría ser usada de muchos lados y tener mucho impacto, pero ocurre que en realidad *solo* se usa en index.php.
En conclusión, estaría totalmente aceptable (y mejor que agregar flash_messages_on_top) mover el bloque home_include después de la inclusión del page_body.tpl.
Por eso diría que sí, se puede *simplemente* mover el bloque de page_body encima del bloque home_include (en vez de agregar una variable).

2020-11-19 17:18 UTC, carlangas159 commented
Se ha cambiado el bloque 
<pre>
     {% block page_body %}
                    {% include 'layout/page_body.tpl'|get_template %}
                {% endblock %}
</pre>
arriba del bloque home_welcome como lo comentado 
"se puede simplemente mover el bloque de page_body encima del bloque home_include"

2020-11-19 17:42 UTC, merged