Mejora para las paginas personalizadas (custompages)
chamilo/chamilo-lms pull request #3619
Opened 2020-11-09 07:04 UTC by aragonc

He realizado una mejora que mejora la presentación en las paginas personalizadas.

![LOGIN](https://user-images.githubusercontent.com/2940509/98509797-e2465700-222f-11eb-8651-7f761625beef.png)

![REGISTRO](https://user-images.githubusercontent.com/2940509/98509795-e2465700-222f-11eb-8b78-a09befabca7a.png)

![RECUPERA CONTRASEÑA](https://user-images.githubusercontent.com/2940509/98509792-e1152a00-222f-11eb-8398-a9a87bcf684e.png)

2020-11-09 14:55 UTC, ywarnier requested changes
Se ve más bonito pero hay que respetar la syntaxis de Chamilo.
Con respeto al favicon.png, no se puede simplemente usar el favicon.ico?
Con respeto al header-logo.svg, porqué los cambias de tamaño? Es SVG, se supone que deberías poder indicar su tamaño en el tag HTML <img>, no?

2020-11-09 14:55 UTC, ywarnier commented on app/Resources/public/css/themes/chamilo/custompage.css
> +@import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap');
No aceptamos la dependencia a fuentes externas en Chamilo. Usar fuentes estándar o incluirlas como ttf

2020-11-09 14:55 UTC, ywarnier commented on custompages/index-unlogged-dist.php
> +$template = new Template(get_lang('SignIn'),false,false,false,false,true,true);
Faltan espacios entre los argumentos de la llamada a la función

2020-11-09 14:55 UTC, ywarnier commented on custompages/lostpassword-dist.php
> +$template = new Template(get_lang('LostPassword'),false,false,false,false,true,true);
Faltan espacios entre los argumentos

2020-11-09 14:55 UTC, ywarnier commented on custompages/registration-dist.php
> +$template = new Template(get_lang('Registration'),false,false,false,false,true,true);
Faltan espacios entre los argumentos

2020-11-09 14:55 UTC, ywarnier commented on main/auth/inscription.php
> +        $form->addButton('register',get_lang('RegisterUser'),null,'primary','btn-block');
Faltan espacios...

2020-11-09 14:55 UTC, ywarnier commented on main/auth/lostPassword.php
> +$form = new FormValidator('lost_password','post','','',[],FormValidator::LAYOUT_GRID);
Faltan espacios...

2020-11-09 14:55 UTC, ywarnier commented on main/auth/lostPassword.php
> +$form->addButtonSend(get_lang('Send'),'submit',false,[],'btn-block',null);
Faltan espacios

2020-11-09 14:55 UTC, ywarnier commented on main/inc/lib/template.lib.php
> +            $cssCustomPage = api_get_path(SYS_CSS_PATH) . $this->themeDir . "custompage.css";
No se usan espacios para las concatenaciones en Chamilo (como en la línea 662 justo arriba).

2020-11-09 14:55 UTC, ywarnier commented on main/inc/lib/template.lib.php
> +                $css[] = api_get_path(WEB_CSS_PATH) . $this->themeDir . 'custompage.css';
Tampoco aquí

2020-11-09 17:34 UTC, aragonc commented on app/Resources/public/css/themes/chamilo/custompage.css
> +@import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap');
Lo quite... para que use el de default.css por defecto

2020-11-09 17:35 UTC, aragonc commented on main/auth/inscription.php
> +        $form->addButton('register',get_lang('RegisterUser'),null,'primary','btn-block');
Corregido en mi fix

2020-11-09 17:35 UTC, aragonc commented on custompages/registration-dist.php
> +$template = new Template(get_lang('Registration'),false,false,false,false,true,true);
Corregido en mi FIX

2020-11-09 17:35 UTC, aragonc commented on main/auth/lostPassword.php
> +$form = new FormValidator('lost_password','post','','',[],FormValidator::LAYOUT_GRID);
Corregido en el fix

2020-11-09 17:35 UTC, aragonc commented on main/inc/lib/template.lib.php
> +            $cssCustomPage = api_get_path(SYS_CSS_PATH) . $this->themeDir . "custompage.css";
Corregido en el fix

2020-11-09 17:40 UTC, aragonc commented on app/Resources/public/css/themes/chamilo/custompage.css
> +@import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&display=swap');
Con respeto al favicon.png, no se puede simplemente usar el favicon.ico?

Porque mande una update en el template.lib.php para usar PNG, para que admita transparencia en el Favicon

El header-logo.svg es un svg con un tamaño 300px de ancho, solo ajuste en el tpl solamente, no afecta en el caso de responsive

2020-11-18 15:06 UTC, ywarnier requested changes

2020-11-19 23:20 UTC, merged