Sesiones: Clase inscrita en una sesion que no aparece en el curso a dentro de la sesion.
chamilo/chamilo-lms pull request #3623
Opened 2020-11-11 18:26 UTC by carlangas159

Actualmente, no se esta mostrando correctamente las clases en una sesion. Con el cambio habilita la posibidad de inscribir clases en cursos o sesiones, 

En una sesion:
![imagen](https://user-images.githubusercontent.com/18097392/98849059-9ad2ed00-2420-11eb-9f9f-210680492427.png)
En un curso:
![imagen](https://user-images.githubusercontent.com/18097392/98849225-e4233c80-2420-11eb-83fc-c568bd0d4665.png)

Tambien se muestra correctamente cuando una clase esta inscrita en un curso o sesion
![imagen](https://user-images.githubusercontent.com/18097392/98849387-1f257000-2421-11eb-868d-5e0eaaa12883.png)

En una sesion 
![imagen](https://user-images.githubusercontent.com/18097392/98849411-29e00500-2421-11eb-8755-b2a1159d7de5.png)

Este cambio puede afectar el comportamiento actual de chamilo ya que el comportamiento actual de esta seccion es:

En un curso, cuando se accede a grupos y posteriormente a clases, se listan las clases del curso y tambien de las sesiones. Sin embargo, cuando se accede a la sesion, no se muestran correctamente las clases inscritas.

@NicoDucou 
BT#17984

2020-11-12 15:05 UTC, AngelFQC commented on main/inc/ajax/model.ajax.php
> +        $options['session_id'] = $_SESSION['id_session'];
Mejor usar `api_get_session_id()`

2020-11-18 15:09 UTC, ywarnier commented on main/user/class.php
> +            $idSession = (int) isset($_GET['id_session']) ? $_GET['id_session'] : 0;
Forma incorrecta de poner `(int)` (por un tema de precendencia)

2020-11-18 15:10 UTC, ywarnier commented on main/user/class.php
> +            $idSession = (int) isset($_GET['id_session']) ? $_GET['id_session'] : 0;
forma incorrecta de usar (int) como filtro (precedencia)

2020-11-18 15:11 UTC, ywarnier commented on main/inc/ajax/model.ajax.php
> +                    $_SESSION['id_session']
mejor usar `api_get_session_id()` aquí también.

2020-11-18 15:46 UTC, ywarnier requested changes
Hay 4 cambios menores que atender.

2020-11-18 15:48 UTC, ywarnier commented
Y hay que actualizar porque hay un conflicto con la 1.11.x actual

2020-11-18 20:56 UTC, carlangas159 commented on main/inc/ajax/model.ajax.php
> +                    $_SESSION['id_session']
Gracias lo he cambiado

2020-11-18 20:56 UTC, carlangas159 commented on main/user/class.php
> +            $idSession = (int) isset($_GET['id_session']) ? $_GET['id_session'] : 0;
Con api_get_session_id no se requiere esta validacion

2020-11-19 16:25 UTC, merged