Ajuste para reporte de venta de lp items BT 17943
chamilo/chamilo-lms pull request #3649
Opened 2020-11-19 20:15 UTC by carlangas159

Se bloquea la edicion de authores y precios para los items de la leccion, habilitandolo solo para administradores mediante api_protect_admin_script.

Si la variable es 'authors','authorlp','authorlpitem', 'price'  y no es administrador (mediante api_is_platform_admin) no se mostrara el elemento en la edicion del item del LP, asi como tambien, no se mostrará el icono en la pantalla.

2020-11-19 23:28 UTC, ywarnier requested changes
Problemas de espacios. Ya voy corrigiendo varios silenciosamente, así que estos te los reporto para que te entrenes a no olvidarlos!

2020-11-19 23:28 UTC, ywarnier commented on main/lp/lp_add_author.php
> +    if(isset($priceItem['value']) && !empty($priceItem['value'])){
Espacios!

2020-11-19 23:28 UTC, ywarnier commented on main/lp/lp_add_author.php
> +$form->addNumeric('price',get_lang('Price'));
Espacio entre parámetros! (después de la coma)

2020-11-19 23:28 UTC, ywarnier commented on main/lp/lp_add_author.php
> +                if(count($sms)>0){
Espacios en las 2 líneas!

2020-11-20 16:28 UTC, carlangas159 commented on main/lp/lp_add_author.php
> +                if(count($sms)>0){
He hecho un commit resolviendo los epacios comentados.

2020-11-20 20:28 UTC, merged