Document : Comment basename($document_to_move['path']) to prevent twice folde
chamilo/chamilo-lms pull request #3660
Opened 2020-11-23 18:21 UTC by carlangas159

When $ _configuration ['enable_add_file_link'] = true; files can be uploaded to the cloud using the url. Then when you want to move to another folder, a failure occurs when placing the destination folder and also the current folder in the database.

In the DocumentManager :: updateDbInfo function it has been modified so that only the path to which it will be moved is set.
![imagen](https://user-images.githubusercontent.com/18097392/99999702-8979d100-2d8e-11eb-81f6-a5b47133d644.png)
For previous events, the corresponding paths must be verified in the c_document table to set the "path" field in the correct location if there are problems with the current links
#3596

2020-11-27 08:00 UTC, jmontoyaa requested changes

2020-11-27 08:00 UTC, jmontoyaa commented on main/inc/lib/document.lib.php
> +     * @param Int    $documentId - Id of specific document
int sin mayúscula

2020-11-27 08:00 UTC, jmontoyaa commented on main/inc/lib/document.lib.php
> +                    $query .= " AND id = $documentId";
Mejor usar iid

2020-11-27 12:36 UTC, merged

2020-11-30 13:31 UTC, carlangas159 commented on main/inc/lib/document.lib.php
> +                    $query .= " AND id = $documentId";
Muchas gracias, use id por que en principio, iid es parte de codigo viejo y no vi diferencias entre id e iid, para normalizarlo era mejor usar id. sin embargo, tomare en cuenta tu comentario.