Posibilidad de añadir información adicional en el correo de confirmación de pago por transferencia
chamilo/chamilo-lms pull request #3669
Opened 2020-11-26 09:52 UTC by nosolored

En la mayoría de las situaciones el usuario que configura el pago por transferencia quieres añadir un mensaje adicional para indicar el procedimiento o las instrucciones del pago para agilizar el proceso. 
Hasta ahora la única posibilidad era editar la cadena de texto "PurchaseDetailsEnd" por lo que requería editar el fichero vía ftp.
Lo que se propone es añadir un campo de texto en la página de "Configuración  de Pagos"
![image](https://user-images.githubusercontent.com/5868981/100335519-5ffeb680-2fd5-11eb-9a8f-8c722734f6f6.png)

2020-11-26 10:07 UTC, ywarnier requested changes
Falta modificar el instalador y el README

2020-11-26 10:07 UTC, ywarnier commented on plugin/buycourses/src/buy_course_plugin.class.php
> +            $sql = "ALTER TABLE $table ADD (info_email_extra TEXT NOT NULL)";
Aunque es aceptable modificar la estructura de una tabla de plugin en vivo, es necesario tener *también* estas instrucciones y una nueva versión informada en el README.md y en el instalador del plugin.
Es una cuestión de coherencia: queremos que el instalador del plugin se pueda analizar para saber exactamente qué estructura de tablas el plugin necesita.

2020-11-29 10:27 UTC, ywarnier commented
Con este último cambio, actualizas el README, pero solo para pedir ejecutar el update.php, pero este update no hace el cambio de info_email_extra si es que ya existe la tabla de configuración del plugin (solo agrega el campo si es que agrega la tabla).
Para evitar esto, se debería modificar update.php para verificar la existencia del campo.
Ahora lo hago.

2020-11-29 11:53 UTC, ywarnier commented
Observo que la implementación no permite una gestión multi-idomas de este mensaje (a menos que se pongan los distintos idiomas en el mensaje mismo). La única forma que veiría para esto sería hacer una tabla de traducciones para el plugin, lo cual probablemente sea exagerado por ahora.

2020-11-29 12:00 UTC, merged

2020-11-29 12:25 UTC, nosolored commented
Gracias @ywarnier