BuyCourses: Center image and put background color to fill it - 18138
chamilo/chamilo-lms pull request #3694
Opened 2020-12-03 16:31 UTC by carlangas159

The design can be broken in the sales catalog when the height adjustment of the images is less than 135px, currently it is set as a maximum of 135px high.
![imagen](https://user-images.githubusercontent.com/18097392/101057492-158fb380-355a-11eb-9f29-423a615a97e5.png)
This is because the current crop plugin does not allow setting a width and height to be able to cut the images properly. Therefore, the user can create smaller images.
![cut](https://user-images.githubusercontent.com/18097392/101057672-4d96f680-355a-11eb-9b6f-d36763b6df2c.png)

To prevent this, adjust the height to a specific measure depending on the screen that is observed by css

For screens smaller than 797px, a height of 220px is established![small_320](https://user-images.githubusercontent.com/18097392/101057815-77501d80-355a-11eb-9b85-de65ce07af21.png)
![small_480](https://user-images.githubusercontent.com/18097392/101057821-78814a80-355a-11eb-9ed8-9dc217b907c4.png)
for screens of 797px or more, a height of 170px is set
![small_600](https://user-images.githubusercontent.com/18097392/101057917-9484ec00-355a-11eb-9a6c-a99d8efaef48.png)
for screens larger than or equal to 991px

![large_1024](https://user-images.githubusercontent.com/18097392/101058058-bda57c80-355a-11eb-8dd1-d4cdda3d28f9.png)

2020-12-04 21:44 UTC, AngelFQC requested changes
Los breakpoints para los media queries deberían ser, al menos, los mismos que usa Bootstrap
```css
@media (min-width: 768px) {}

@media (min-width: 992px) {}

@media (min-width: 1200px) {}
```

2020-12-04 21:44 UTC, AngelFQC commented on plugin/buycourses/resources/css/style.css
> +        height: 155px;
El selector correcto debería aplicarse a `img` porque el figure sólo actúa como contenedor.
`.col-sm-6 .items-course .items-course-image figure`

2020-12-05 03:12 UTC, carlangas159 commented on plugin/buycourses/resources/css/style.css
> +        height: 155px;
Nop,  aplica a figure, de ese modo si tienes una imagen más pequeña no se deforma y si tienes una imagen muy grande se ajusta. Es por ello que figure actúa como un contenedor que puede deformarse para que la imagen se mantenga con su aspecto real.

2020-12-07 22:00 UTC, AngelFQC commented on plugin/buycourses/resources/css/style.css
> +        height: 155px;
Entonces el título del PR está mal 😄  Porque la imagen no se centra
![imagen](https://user-images.githubusercontent.com/1697880/101410462-5d417280-38ad-11eb-8c47-a5156526875f.png)

Creo, igual, que es mejor forzar el ancho de la imagen, porque se ve mucho espacio vacío cuando la imagen es pequeña.

2020-12-07 22:42 UTC, carlangas159 commented on plugin/buycourses/resources/css/style.css
> +        height: 155px;
Intente centrarlo, y en resoluciones para pc se ve muy bien, sin embargo, cuando se observa en dispositivos pequeños, dependiedo de que ancho tengas, la imagen no se centraba correctamente. De hecho se podia colocar encima del titulo. 

Sin embargo, como comentaste, si el usuario coloca una imagen pequeña, deberia cambiarla, si hago que una imagen pequeña (ejempo 48 px) se ajuste, no se veria correctamente, esto solo acomoda la consecuencia y no la causa. El crop no deberia permitir imagenes menores a un cierto limte pero el crop actual no permite esa opcion y ya no tiene soporte

2020-12-07 22:44 UTC, carlangas159 commented on plugin/buycourses/resources/css/style.css
> +        height: 155px;
Ya he cambiado el titulo del pr, estas en lo cierto. Tambien sobre este proceso de encapsulacion, se puede extender a poder hacerle zoom a la imagen cuando se hace un hover por ejemplo. Sin embargo, podrian ser muchos cambios y no estoy seguro que sea pertinente hacer muchas modificaciones

2020-12-12 16:41 UTC, ywarnier commented
Sería mejor que sea coherente, sí.

2020-12-15 17:30 UTC, carlangas159 commented on plugin/buycourses/resources/css/style.css
> +        height: 155px;
Para mantener la coherencia, he cambiado la figure por img.

2021-08-10 12:01 UTC, ywarnier commented
I believe this is fixed by 930e3f0760 as well as https://github.com/chamilo/chamilo-lms/pull/3715 is

2021-08-10 12:01 UTC, closed without merging