SkillsWheel: Rueda responsiva, Tamaño de iconos de competencia correctos, Colores de competencia equivocados
chamilo/chamilo-lms pull request #3732
Opened 2020-12-23 21:14 UTC by carlangas159

Se ajusta la rueda de competencias a la ventana, tambien se le establece un minimo de alto y ancho de 200 px.

![imagen](https://user-images.githubusercontent.com/18097392/103036943-db05af00-4538-11eb-8104-0589149be5b6.png)

En cuanto a las competencias, la imagen de las competencias, se ajusta solo un poco su altura para que sea coherente.

Tambien se evalua de donde proviene la consulta con el fragmento de codigo:
<pre>
    if (strpos($_SERVER['HTTP_REFERER'], "/main/admin/skills_wheel.php") !== false) {
            $userId = 0;
        }
</pre>
para evitar que se cargen las competencia de los administradores.

 #3731

2020-12-28 19:14 UTC, AngelFQC requested changes

2020-12-28 19:14 UTC, AngelFQC commented on main/inc/ajax/skill.ajax.php
>          echo json_encode($skills);
Creo que es mejor que si viene de /main/admin/, entonces no se llame a `$skill->getUserSkills`. 

Porque como está ahora, igual se estaría consultando a la DB por skill_rel_user con un user que es 0.

2020-12-29 02:55 UTC, carlangas159 commented on main/template/default/skill/skill_wheel.js.tpl
> +        .attr("min-height", "200px")
No es parte del svg sino del div que lo contiene, esto es para que la rueda no se desborde de la pantalla, el svg permanece igual.

2020-12-29 03:00 UTC, carlangas159 commented on main/inc/ajax/skill.ajax.php
>          echo json_encode($skills);
Esa función se usa en el admin y también en las competencias del usuario. Por lo tanto se evalúa que si viene del administrador no se consulte usuario a la base de datos para que no muestre la coloración verde si has obtenido las competencias con el usuario de administración que está consultando la rueda de competencias del sistema y no necesariamente la rueda de sus competencias, la mejor solución sin modificar todas las funciones de Ajax es solo evaluar antes de la función si proviene de administración y también se evita la sobrecarga de la función que genera los datos necesarios para la exportación de valores de la rueda de competencias.

2021-08-10 14:59 UTC, merged