Social: Añadido Boton de compartir certificacion en LinkedIn BT#17468 - refsBT#17468
chamilo/chamilo-lms pull request #3750
Opened 2021-01-12 16:24 UTC by carlangas159

Se añade la posibilidad de compartir una competencia adquirida a traves de linked in
![imagen](https://user-images.githubusercontent.com/18097392/104340852-1f94c280-54c7-11eb-8e8e-88bcf7d3b1e5.png)
Como ejemplo el siguiente enlace
https://www.linkedin.com/profile/add?certId=1&certUrl=https://Your_Chamilo_Url/badge/1&isFromA2p=true&issueMonth=12&issueYear=2020&name=HUMILDAD&organizationId=1337

Esto envia a una pagina de publicacion de Linked In en la cual, se le debe dar a Guardar para ser añadido al perfil. 
Teniendo en cuenta que la vista de linked in permite seleccionar la empresa, se debe tener en cuenta el id de la organizacion para que sea compartida automaticamente para ello, se añade en configuration.php la variable
$_configuration['settings_meta_linkedin_organization_id'] = false;
al cual, debe ser el id de la organizacion, por ejemplo el de LinkedIn es 1337.

![imagen](https://user-images.githubusercontent.com/18097392/104341337-afd30780-54c7-11eb-83d8-08f6a97b903c.png)

2021-01-12 17:15 UTC, AngelFQC requested changes

2021-01-12 17:15 UTC, AngelFQC commented on main/template/default/skill/issued.tpl
> +                </a>
El campo `certUrl` debería estar codificado como url. Porque al ser una url, los parámetros que vienen después de esta se pueden confundir como que pertenecen a esta.

Mejor crear la url con [`url_encode`](https://twig.symfony.com/doc/2.x/filters/url_encode.html) en twig o con `http_build_query` con php

2021-01-12 17:15 UTC, AngelFQC commented on main/badge/issued_all.php
> +    }
Mejor usar un api_get_configuration_value, algo como
```php
$linkedInOrg = api_get_configuration_value('settings_meta_linkedin_organization_id');

if ($linkedInOrg !== false) {
    $linkedinOrganizationId = $linkedInOrg;
}

2021-01-12 20:20 UTC, carlangas159 commented on main/badge/issued_all.php
> +    }
Gracias angel, ten en cuenta que '&organizationId=' se debe mantener ya que se eliminaria de no tener ifnormacion

2021-01-12 20:37 UTC, AngelFQC commented on main/badge/issued_all.php
> +    }
Entonces
```php
$linkedinOrganizationId = "&organizationId=$linkedInOrg";
```

2021-01-14 17:14 UTC, AngelFQC approved these changes

2021-01-14 17:15 UTC, merged