Mostrar u Ocultar el numero de la pregunta de un ejercicio - 18450
chamilo/chamilo-lms pull request #3825
Opened 2021-03-17 19:28 UTC by carlangas159

Cuando esta habilitado. Se activa la posibilidad de ocultar el numero de la pregunta durante el ejercicio. Para esto se debe ir a la configuración del ejercicio
![image](https://user-images.githubusercontent.com/18097392/111526057-4328f300-872c-11eb-8883-e21a8315ede2.png)
y seleccionar Si.

Realizada la configuración, se puede validar presentando el ejercicio, donde en condiciones normales estará el numero de la pregunta 
![image](https://user-images.githubusercontent.com/18097392/111526225-78354580-872c-11eb-8cad-9972722b2178.png)
No aparecerá ningún numero 
![image](https://user-images.githubusercontent.com/18097392/111526469-c9ddd000-872c-11eb-8f13-2e62686f509b.png)

2021-03-17 20:58 UTC, AngelFQC requested changes
No sé si quizás mejor se pueda extender el uso de la variable de configuración `allow_quiz_results_page_config` que ya agrega un sólo campo en la base de datos pero que sirve para agregar varias configuraciones.

2021-03-17 20:58 UTC, AngelFQC commented on main/exercise/question.class.php
> +        if (!$showHideConfiguration) return 0;
```
if (!$showHideConfiguration) {
    return 0;
}
```

2021-03-17 20:58 UTC, AngelFQC commented on main/exercise/question.class.php
> +                return (int)$result[0]['active'];
Espacio después del paréntesis

2021-03-17 20:58 UTC, AngelFQC commented on main/exercise/exercise.class.php
> +            if ($showHideConfiguration ) {
Espacio de más antes del paréntesis de cierre

2021-03-17 20:58 UTC, AngelFQC commented on main/exercise/exercise.class.php
> +            if ( $showHideConfiguration ) {
Espacios de más entre los paréntesis

2021-03-17 20:58 UTC, AngelFQC commented on main/exercise/exercise.class.php
> +            if ( $showHideConfiguration ) {
Espacios de más entre los paréntesis

2021-03-17 20:58 UTC, AngelFQC commented on main/exercise/exercise.class.php
> +        $this->setHideShowQuestionNumber($form->getSubmitValue('hide_question_number'));
Validar que la variable `hide_question_number` esté habilitada para poder usar el campo  con getSubmitValue

2021-03-17 20:58 UTC, AngelFQC commented on main/exercise/exercise.class.php
> +            $this->hideQuestionNumber = (int) $value ;
Espacio de más antes del punto y coma

2021-03-19 21:11 UTC, carlangas159 commented
Queda en espera por comentarios de @ywarnier sobre campos en la base de datos.

2021-03-22 15:22 UTC, AngelFQC commented on main/exercise/exercise.class.php
> +            $showHideConfiguration = api_get_configuration_value('hide_question_number');
Usar solo un `$showHideConfiguration = api_get_configuration_value('hide_question_number');` dentro de la misma función

2021-03-22 15:44 UTC, AngelFQC commented on main/exercise/question.class.php
> +                    q.hide_question_number AS `active`
backticks  no

2021-05-03 23:01 UTC, merged