Course: Fix unsubscribe user button doesn't work in home and sort courses pages - refs #3854
chamilo/chamilo-lms pull request #3885
Opened 2021-05-21 21:54 UTC by christianbeeznest

2021-06-03 22:47 UTC, AngelFQC requested changes

2021-06-03 22:47 UTC, AngelFQC commented on main/auth/sort_my_courses.php
> +                        ?>
El formulario permite una confirmación antes de realizar la acción.
Pero también he mandado un commit para corregir `auth/courses.php?action=unsubscribe` 5c478c7b27afed056420605fdadbd475e14d3b5b. Y con ese commit el formulario se puede quedar, pero cambiando el method de post a get.

2021-06-03 22:47 UTC, AngelFQC commented on main/inc/lib/SortableTableFromArrayConfig.php
> +
Estas modificaciones parecen venir de otro PR

2021-06-03 22:47 UTC, AngelFQC commented on main/inc/lib/course.lib.php
> +                    api_get_path(WEB_CODE_PATH).'auth/courses.php?action=unsubscribe&course_code='.$courseCode
En el commit 5c478c7b27afed056420605fdadbd475e14d3b5b que envié lo dejé como `unsubscribe`

2021-08-12 11:28 UTC, ywarnier commented
@AngelFQC, podrías hacer merge de este PR por favor, ya que has hecho cambios relacionados? Será más fácil para ti y más rápido. Gracias.

2021-08-19 18:55 UTC, AngelFQC commented
This PR includes commits from other PRs.
But the fix to the issue was made in this commit ab4bc19c10bdb627351208213eae045bd2e8afaf

2021-08-19 18:55 UTC, closed without merging