PR Document List
chamilo/chamilo-lms pull request #3889
Opened 2021-05-28 14:56 UTC by tonyidbeeznest

Fix Request Number

2021-05-28 22:25 UTC, AngelFQC requested changes
Indicate the number of the issue related to this PR

2021-05-28 22:25 UTC, AngelFQC commented on main/document/document.php
> +                const response = JSON.parse(data)
For compatibility use `var` for JS. No `const`, no `let`

2021-05-28 22:25 UTC, AngelFQC commented on main/document/document.php
> +        let requests = [];
For compatibility use `var` for JS. No `const`, no `let`

2021-05-28 22:25 UTC, AngelFQC commented on main/inc/lib/document.lib.php
> +        $id = (int)$id;
Missin space after cast `)`

2021-05-28 22:25 UTC, AngelFQC commented on main/inc/lib/document.lib.php
> +    }
Better find the way to reuse the function `DocumentManager::getTotalFolderSize` to avoid duplicated code

2021-05-28 22:25 UTC, AngelFQC commented on main/document/document.php
> +                    . '" data-id= "' . $document_data['id']
No spaces around the concatenate operator

2021-05-28 22:25 UTC, AngelFQC commented on main/document/document.php
> +            url:"' . $getSizesURL . '&requests="+requests,
Spaces

2021-06-02 18:09 UTC, AngelFQC requested changes

2021-06-02 19:20 UTC, tonyidbeeznest commented on main/inc/lib/document.lib.php
> +     * @param bool   $by_id             = default true, if is getting size by document id or false if getting by path
Flintci recommends like this, if not, an error appears. check this test: https://flintci.io/repositories/1013/analyses/61970

2021-06-02 19:27 UTC, AngelFQC commented on main/inc/lib/document.lib.php
> +     * @param bool   $by_id             = default true, if is getting size by document id or false if getting by path
Yes, you can align the parameters/properties name with the comments.
But I meant that the comment should be in uppercase first word, without the = sign.

2021-06-16 21:44 UTC, closed without merging