Update Session: Feat web service to Update a session #18924
chamilo/chamilo-lms pull request #3916
Opened 2021-06-21 21:02 UTC by tonyidbeeznest

2021-06-21 21:59 UTC, AngelFQC requested changes

2021-06-21 21:59 UTC, AngelFQC commented on main/inc/lib/sessionmanager.lib.php
> +    public static function get_session_by_id($id)
Use camelCase for methods

2021-06-21 21:59 UTC, AngelFQC commented on main/inc/lib/sessionmanager.lib.php
> +    public static function get_session_by_id($id)
Aunque existen dos métodos que llegan a hacer lo mismo

https://github.com/chamilo/chamilo-lms/blob/5e4a6f40a93217d23643b85ebbe08f6d4e9fbffc/main/inc/lib/sessionmanager.lib.php#L49

https://github.com/chamilo/chamilo-lms/blob/5e4a6f40a93217d23643b85ebbe08f6d4e9fbffc/main/inc/lib/sessionmanager.lib.php#L7660

2021-06-22 09:32 UTC, NicoDucou commented
Validado al nivel funcional, esperando validacion del codigo ahora.

2021-06-22 23:44 UTC, AngelFQC requested changes

2021-06-22 23:44 UTC, AngelFQC commented on main/inc/lib/sessionmanager.lib.php
> +    public static function update_session(
Aunque creo que este método no debería estar aquí puesto que ya existe un `SessionManager::edit_session`. Debería estar dentro de la clase Rest por ser un update relacionado al web service.

2021-06-22 23:44 UTC, AngelFQC commented on main/inc/lib/webservices/Rest.php
> +        }
Aquí es mejor lanzar una Exception en caso de error ya que las excepciones son capturadas en v2.php.

2021-06-22 23:44 UTC, AngelFQC commented on main/inc/lib/webservices/Rest.php
> +                'message' => "Session updated",
Usar get_lang para el mensaje

2021-06-22 23:44 UTC, AngelFQC commented on main/inc/lib/sessionmanager.lib.php
> +        $tbl_session = Database::get_main_table(TABLE_MAIN_SESSION);
camelCase

2021-06-22 23:44 UTC, merged