Course Creation Form: Add configuration setting to Course Category and Course Code - refs #18889
chamilo/chamilo-lms pull request #3919
Opened 2021-06-23 15:50 UTC by tonyidbeeznest

2021-06-23 22:55 UTC, AngelFQC requested changes

2021-06-23 22:55 UTC, AngelFQC commented on main/install/configuration.dist.php
> +//$_configuration['course_creation_form_set_course_category_mandatory'] = false;
Agregar las nuevas variables antes de la línea 1963 que indica "keep this at the end"

2021-06-23 22:55 UTC, AngelFQC commented on main/admin/course_add.php
Quitando los inputs del form hace que no reciban los valores en $_POST y se lanzan warnings por eso
```
PHP Warning:  Undefined array key "visual_code" in /var/www/chamilo1/main/admin/course_add.php on line 234, referer: https://chamilo1.test/main/admin/course_add.php
```

2021-06-23 22:55 UTC, AngelFQC commented on main/create_course/add_course.php
> +    $form->addRule('category_code', get_lang('ThisFieldIsRequired'), 'required');
El campo de categoría está oculto por defecto. Sería mejor que si se habilita com obligatorio se muestre antes del botón de "parámetros avanzados"

2021-06-24 15:23 UTC, tonyidbeeznest commented on main/admin/course_add.php
No logro reproducir ese warning, he creado los cursos pero no me sale ningún error o aviso. Como reproduzco eso?

2021-06-24 15:27 UTC, AngelFQC commented on main/admin/course_add.php
Quizás no tienes los display_errors habilitados. Pero podrás verlo en el error_log de php.

2021-06-24 22:08 UTC, AngelFQC approved these changes

2021-06-25 08:32 UTC, merged