Maintenance tool : Implement Common Cartridge 1.3 - refs #2747
chamilo/chamilo-lms pull request #3921
Opened 2021-07-02 08:24 UTC by christianbeeznest

2021-07-23 20:52 UTC, AngelFQC requested changes
Las clases con prefijo `Cc` parecen ser externas, y no cumplen con las convenciones de código de Chamilo. Verificar posibilidad e agregarlas con composer

2021-07-23 20:52 UTC, AngelFQC commented on main/common_cartridge/cc13_import.php
> +$template->assign('info_msg', $infoMsg);
No es necesario agregar una variable Twig para mostrar mensaje. Los mensajes se pueden mostrar directamente usando `Display::addFlash`

2021-07-23 20:52 UTC, AngelFQC commented on main/common_cartridge/cc13_import.php
> +$infoMsg = Display::return_message(get_lang('ImportCcInstructions'), 'normal', false);
$infoMsg es asignado lineas arriba y reasignado aquí 🤔

2021-07-23 20:52 UTC, AngelFQC commented on main/template/default/common_cartridge/import_cc.tpl
> +    $(document).ready(function(){
Lo recomendado es usar 
```javascript
$(function() {
  // Handler for .ready() called.
});
```

2021-07-23 20:52 UTC, AngelFQC commented on main/template/default/common_cartridge/import_cc.tpl
> +            $("#loader").html('<div class="wobblebar-loader"></div><p> {{ 'ProcessingImportPleaseDontCloseThisWindowThisActionMayTakeLongTimePlaseWait' | get_lang }} </p>');
Sin espacios antes ni después del operador `|`

2021-07-23 20:52 UTC, AngelFQC commented on main/common_cartridge/autoload.php
> +spl_autoload_register('loadImportConverter');
Existe algún repositorio que composer pueda gestionar para no agregar un autoload manualmente?

2021-07-23 20:52 UTC, AngelFQC commented on main/common_cartridge/export/Cc13ExportConvert.php
> +    public static function export($objCourse) {
La llave en la siguiente línea

2021-07-23 20:52 UTC, AngelFQC commented on main/common_cartridge/export/Cc13ExportConvert.php
> +    public static function createImscc($backupDir, $objCourse) {
Llave en la siguiente línea

2021-07-23 20:52 UTC, AngelFQC commented on main/common_cartridge/cc13_export.php
> +        $course = $cb->build(0, null, false, array_keys($_POST['resource']), $_POST['resource']);
Verificar que $_POST['resource'] está definido

2021-07-23 20:52 UTC, AngelFQC commented on main/common_cartridge/cc13_export.php
> +    $imsccFile = Cc13ExportConvert::export($course);
$course es asignado dentro del if anterior, por lo que si el if no se cumple entonces $course aquí no estaría definido

2021-07-23 20:52 UTC, AngelFQC commented on main/common_cartridge/cc13_export.php
> +    if ($imsccFile !== FALSE) {
false, en minúsculas.

2021-07-23 20:52 UTC, AngelFQC commented on main/common_cartridge/cc13_export.php
> +    }
Para el caso en que se va a mostrar un enlace con clases de botón, es mejor usar Display::toolbarButton

2021-07-23 20:52 UTC, AngelFQC commented on main/common_cartridge/cc13_export.php
> +        RESOURCE_WIKI
Como al final de cada elemento del array

2021-08-11 23:10 UTC, ywarnier commented on main/common_cartridge/export/src/CcAssesment.php
> +}
Dos cosas sobre este archivo: 
1) si fue copiado (aunque sea parcialmente) desde otra fuente, tiene que indicar la fuente
2) normalmente (según PSR) debe ser una clase por archivo. No se pueden poner más de una clase en un mismo archivo.

2021-08-18 20:58 UTC, closed without merging