Certificate Generation: Add checkbox conditional
chamilo/chamilo-lms pull request #3935
Opened 2021-07-30 02:09 UTC by tonyidbeeznest

2021-07-30 15:26 UTC, NicoDucou commented on main/inc/ajax/myspace.ajax.php
> +        }
No se necesita verificar si la variable de idioma esta existante, la vamos a agregar

2021-07-30 15:26 UTC, NicoDucou commented on main/inc/ajax/myspace.ajax.php
> +        }
Aqui tampoco es necesario revisar si la variable de idioma existe.

2021-08-03 15:49 UTC, AngelFQC requested changes

2021-08-03 15:49 UTC, AngelFQC commented on main/inc/ajax/myspace.ajax.php
> +        $sId = (int) $_REQUEST['session_to_export'];
Validar que student y session_to_export existen, antes de hacer el cast

2021-08-03 15:49 UTC, AngelFQC commented on main/inc/ajax/myspace.ajax.php
> +        $message = get_lang('HideConnectionTime', true);
El segundo parámetro de get_lang no es necesario en este caso

2021-08-03 15:49 UTC, AngelFQC commented on main/inc/ajax/myspace.ajax.php
> +        $messageBtn = get_lang('GenerateCertificate', true);
El segundo parámetro de get_lang no es necesario en este caso

2021-08-03 15:49 UTC, AngelFQC commented on main/mySpace/myStudents.php
> +                    api_get_path(WEB_CODE_PATH).'inc/ajax/myspace.ajax.php?'
Usar WEB_AJAX_PATH

2021-08-09 13:14 UTC, ywarnier commented
@tonyidbeeznest no se si no recibiste el aviso, pero faltan varios detalles en este PR. La corrección de Flint en este caso es correcta (hay una línea blanca demás en un switch/case).

2021-08-10 16:52 UTC, AngelFQC approved these changes

2021-08-10 17:09 UTC, merged