Search : Add search diagnosis from preprodparkur - #BT18899
chamilo/chamilo-lms pull request #3939
Opened 2021-08-04 15:23 UTC by christianbeeznest

2021-08-09 20:51 UTC, AngelFQC requested changes
La variable de configuración allow_search_diagnostic es agregada pero no es usada.

No modificar los archivos JS CSS que estén en public/main/search/

2021-08-17 11:31 UTC, jmontoyaa commented on public/main/inc/ajax/extra_field.ajax.php
> +                'tag' => $tag,
@christianbeeznest  por qué ese cambio?

2021-08-17 13:43 UTC, jmontoyaa commented on public/main/inc/lib/pear/HTML/QuickForm/element.php
> +            return eval("return (isset(\$values$myVar)) ? \$values$myVar : null;");
En que momento se necesita ese cambio? Ejemplo?

2021-08-17 13:49 UTC, christianbeeznest commented on public/main/inc/ajax/extra_field.ajax.php
> +                'tag' => $tag,
Hola Julio, el problema era que no se podia crear los campos de tipo tags desde el input.

2021-08-17 14:06 UTC, christianbeeznest commented on public/main/inc/lib/pear/HTML/QuickForm/element.php
> +            return eval("return (isset(\$values$myVar)) ? \$values$myVar : null;");
Hola Julio, al comienzo no se podia guardar nada del formulario en el search diagnosis, hay algunos attributos como el name que son de esta forma name="extra_filiere[extra_filiere]" con corchetes, agregando el eval que si esta en la version 1.11.x se corrige.

2021-08-18 08:47 UTC, merged

2021-08-18 08:49 UTC, jmontoyaa commented on public/main/inc/lib/pear/HTML/QuickForm/element.php
> +            return eval("return (isset(\$values$myVar)) ? \$values$myVar : null;");
eval removido con:

https://github.com/chamilo/chamilo-lms/commit/38b939854ec0361624c6586bdf4748e37eca7e92

2021-08-18 08:52 UTC, jmontoyaa commented on public/main/inc/ajax/extra_field.ajax.php
> +                'tag' => $tag,
Corregido, ese query fue movido y corregido en la clase TagRepository:

https://github.com/chamilo/chamilo-lms/commit/837dd6fedfceb95b930fd73146fd81f425be4e51#diff-a74a471c2b6e7d8f62e6245c8c7862f270c6491e0134cf4425d6789ec4592060R24