Quiz Tool : Add new "file upload" type of question - BT18258
chamilo/chamilo-lms pull request #3944
Opened 2021-08-16 09:03 UTC by christianbeeznest

2021-08-16 13:05 UTC, NicoDucou commented
At a functional level it is all good for me.

2021-08-16 13:08 UTC, NicoDucou commented
@ywarnier we are missing a new icon for this new type of question.

2021-08-16 16:44 UTC, AngelFQC requested changes

2021-08-16 16:44 UTC, AngelFQC commented on main/inc/ajax/exercise.ajax.php
> +        if (!empty($_FILES)) {
`api_protect_course_script` ya se llama al inicio del archivo (L14), mejor agregar llamada a `api_block_anonymous_users`

2021-08-16 16:44 UTC, AngelFQC commented on main/inc/lib/exercise.lib.php
> +                                  console.log(file);
Console 👀

2021-08-16 16:44 UTC, AngelFQC commented on main/inc/lib/exercise_show_functions.lib.php
> +    {
`) {` en la misma línea para este caso

2021-08-16 16:44 UTC, AngelFQC commented on main/inc/lib/exercise_show_functions.lib.php
> +            if ($questionScore > 0 || !empty($comments)) {
La variable $comments no está definida en la función.
Hace falta un `$comments = Event::get_comments($exe_id, $questionId);`

2021-08-16 23:57 UTC, ywarnier commented
He agregado los iconos aquí: b5fb53e9fca5c47cd5f6418b8947d9ab1c49a91d

2021-08-17 14:51 UTC, christianbeeznest commented
Las observaciones estan revisadas en el ultimo commit . Gracias.

2021-08-18 08:05 UTC, NicoDucou commented
Todo conforme para mi, solo quedan los comentarios de Flint

2021-08-19 08:58 UTC, merged