WIP: Course Maintenance - Implement Common Cartridge import and expor…
chamilo/chamilo-lms pull request #3948
Opened 2021-08-18 21:26 UTC by christianbeeznest

…t - refs#2747

2021-08-19 09:01 UTC, ywarnier commented
Cuidado con las observaciones de codacy/flintci: hay nuevas variables en $lower_camel_case en vez de $upperCamelCase

2021-08-24 14:52 UTC, ywarnier requested changes
Más que todo, poner en mayúsculas las constantes y verificar unas variables no usadas reportadas por Codacy. También ver el tema de licencia de las librerías de terceros.

2021-08-24 14:52 UTC, ywarnier commented on composer.json
> +	    "plugin"
Indentación incorrecta (no uses tabs)

2021-08-24 14:52 UTC, ywarnier commented on main/common_cartridge/export/src/CcVersion13.php
> +    const basiclti = 'imsbasiclti_xmlv1p3';
Codacy tiene un punto aquí... si no defines las constantes en mayúsculas, luego será difícil encontrarlas para modificarlas (ver unas líneas a bajo: `assessment` es una palabra relativamente común en el resto de Chamilo.

2021-08-24 14:52 UTC, ywarnier commented on main/common_cartridge/export/src/base/XMLGenericDocument.php
> +     * Enter description here ...
No es la mejor descripción de método que haya encontrado...

2021-08-24 14:52 UTC, ywarnier commented on main/common_cartridge/export/src/lib/assesment/CcAssesmentHelper.php
> +     * Enter description here ...
Falta descripción o eliminar el texto por defecto

2021-08-24 14:52 UTC, ywarnier commented on main/common_cartridge/export/src/lib/assesment/CcQtiMetadata.php
> +}
Misma cosa aquí con las constantes.

2021-08-24 14:52 UTC, ywarnier commented on main/common_cartridge/export/src/lib/assesment/CcQtiProfiletype.php
> +    const essay = 'cc.essay.v0p1';
Y aquí también las constantes

2021-08-24 14:52 UTC, ywarnier commented on main/common_cartridge/export/src/lib/assesment/CcQtiTags.php
> +    const hintmaterial = 'hintmaterial';
Y aquí también

2021-08-24 14:52 UTC, ywarnier commented on main/common_cartridge/export/src/lib/assesment/CcQtiValues.php
> +    const htmltype = 'text/html';
Y aquí también: constantes en mayúsculas

2021-08-24 14:52 UTC, ywarnier commented on main/common_cartridge/export/src/lib/ccdependencyparser.php
> +function getDepFiles($manifestroot, $fname, $folder, &$filenames)
Aquí una descripción del método vendría bien porque "getDepFiles" no se entiende por si mismo. Se trata de archivos de dependencias, algo así?
```
/**
 * Gets the dependency files of the $fname file
 */
```
o algo así?

2021-08-24 14:52 UTC, ywarnier commented on main/common_cartridge/import/src/base/validator/CcValidateType.php
> +    const weblink_validator13 = 'ccv1p3_imswl_v1p3.xsd';
Aquí constantes en mayúsculas también

2021-08-24 20:40 UTC, christianbeeznest commented
Gracias Yannick, las ultimas observaciones estan corregidas.

2021-08-24 21:35 UTC, merged