Student report: Add option to hide the column Time in lp tables in st…
chamilo/chamilo-lms pull request #3955
Opened 2021-08-27 21:44 UTC by christianbeeznest

…udent follow export - refs BT#19073

2021-08-30 09:43 UTC, NicoDucou commented
Todo conforme para mi a nivel funcional, solo falta revision de codigo para acceptar este PR.

2021-08-31 16:53 UTC, AngelFQC requested changes

2021-08-31 16:53 UTC, AngelFQC commented on main/mySpace/student_follow_export.php
> +    $hideConnectionTime = (bool) $values['hide_connection_time'];
Si no se marca el checkbox de hide_connection_time, aquí se lanza un E_NOTICE. Cambiarlo por un `isset($values['hide_connection_time'])`

2021-08-31 17:03 UTC, merged

2021-08-31 17:06 UTC, AngelFQC commented on main/mySpace/student_follow_export.php
> +    $hideConnectionTime = (bool) $values['hide_connection_time'];
Corregido c1a22895b9e59bf887e5317891ddeeee7bd86326