Lp: Implement partial surveys in lps and base survey in sessions - refs BT#19049
chamilo/chamilo-lms pull request #4072
Opened 2021-11-18 04:45 UTC by christianbeeznest

2021-11-18 04:53 UTC, christianbeeznest commented
Nuevas variables de idioma para agregar en el translate

$CreateANewSurvey = "Create a new survey";
$NewSurveyCreated = "New survey created";
$AddSurveyToCourse = "Add survey to course";
$EditCurrentSurvey = "Edit current survey";
$CreateTheSurvey = "Create the survey";
$MoveTheCurrentSurvey = "Move the current survey";
$EditCurrentSurvey = "Edit current survey";

2021-11-19 22:22 UTC, AngelFQC requested changes

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/fillsurvey.php
> +                    $sessionCondition = api_get_session_condition($sessionId, true, false, 'sa.session_id');
Lo mismo para api_get_session_condition

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/fillsurvey.php
> +                $sessionCondition = api_get_session_condition($sessionId, true, false, 'survey_answer.session_id');
api_get_session_condition...

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/fillsurvey.php
> +}
La condición me da a entender que se quiere mostrar el contenido del curso base en la sesión, pero el tercer parámetro de `api_get_session_condition` (`$with_base_content = false` por defecto), hace lo contrario.

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/survey.lib.php
> +            $sessionCondition = api_get_session_condition($sessionId);
api_get_session_condition...

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +            $sessionCondition = api_get_session_condition($sessionId);
api_get_session_condition...

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +                $sessionCondition = api_get_session_condition($sessionId);
api_get_session_condition...

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +                $sessionCondition = api_get_session_condition($sessionId);
api_get_session_condition...

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +            $sessionCondition = api_get_session_condition($sessionId);
api_get_session_condition...

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +            $sessionCondition = api_get_session_condition($sessionId);
api_get_session_condition...

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +            $sessionCondition = api_get_session_condition($sessionId);
api_get_session_condition...

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +            $sessionCondition = api_get_session_condition($sessionId);
api_get_session_condition...

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +            $sessionCondition = api_get_session_condition($sessionId);
api_get_session_condition...

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +            $sessionCondition = api_get_session_condition($sessionId);
api_get_session_condition...

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +            $sessionCondition = api_get_session_condition(api_get_session_id(), true, true);
api_get_session_condition... Tercer parámetro es true

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +            $sessionCondition = api_get_session_condition($sessionId, true, true);
Aquí también es true

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +            $sessionCondition = api_get_session_condition($sessionId, true, true, 'survey.session_id');
api_get_session_condition...

2021-11-19 22:22 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
> +            $sessionCondition = api_get_session_condition($sessionId);
api_get_session_condition...

2021-11-19 22:31 UTC, AngelFQC commented
> $CreateANewSurvey = "Create a new survey";
> $CreateTheSurvey = "Create the survey";

Ya existe $CreateSurvey

> $NewSurveyCreated = "New survey created";

Ya existe `$SurveyAdded`

> $AddSurveyToCourse = "Add survey to course";
Agregada

> $EditCurrentSurvey = "Edit current survey";

Ya existe `$ModifySurveyInformation`

> $MoveTheCurrentSurvey = "Move the current survey";
Agregada

2021-11-22 18:59 UTC, christianbeeznest commented
Gracias @AngelFQC  , observaciones verificadas en el siguiente commit

2021-11-23 04:17 UTC, AngelFQC requested changes

2021-11-23 04:17 UTC, AngelFQC commented on main/survey/surveyUtil.class.php
>          $insertId = Database::insert_id();
Mejor usar la entidad CSurveyAnswer

2021-11-24 21:29 UTC, christianbeeznest commented on main/survey/fillsurvey.php
> +$sql .= api_get_session_condition($sessionId, true, true);
Agregado la condicion en el ultimo commit

2021-11-26 00:48 UTC, christianbeeznest commented
Variable de idioma :
$FilterByLp = "Filter by learnpath item";

2021-11-26 07:03 UTC, merged

2021-11-26 07:04 UTC, NicoDucou commented
He acceptado este PR aun falta permitir ver en los reportes del curso base las respuestas enviadas en las sesiones si $_configuration['show_surveys_base_in_sessions'] === true