[PLUGIN] IMS/LTI option to add tool to sessions
chamilo/chamilo-lms pull request #4114
Opened 2021-12-27 19:15 UTC by juan-cortizas-ponte

This pull request adds the option to add the LTI tool to sessions so campus administrators doesn´t have to add the tool to the base course

2022-01-04 19:11 UTC, AngelFQC requested changes
Hola @juan-cortizas-ponte 

He hecho 4 commits para corregir algunas cosas del PR https://github.com/AngelFQC/chamilo-lms/commits/1.11.x.ims-lti-plugin-add-tool-to-sessions

- f84e7fb387f79c9453ff8be39788a60c4fd1f9cd 
- 9eaf57fe2756b2290f011492a41ae4f55e6eceef 
- 34e692237c9dabcb388ceace99abdc99941c4588 
- 74c1801182c799e319e600013a3bcfce185f4a7d

También hay un conflicto sin resolver por un cambio reciente en la rama 1.11.x

El soporte para sesiones parece funcionar bien para realizar el launch de las herramientas, pero ya que LTI tiene servicios adicionales, faltaria hacer una prueba dentro del contexto de solo sesión. Por ejemplo, el servicio de Outcomes de LTI 1 (que permite almacenar calificaciones de la herramienta LTI en el gradebook) no se puede configurar dentro de un curso sesión. En un curso base se haría desde _Configuración del curso_ -> _IMS/LTI / Configurar herramienta externa_ -> _Permitir calificar en la herramienta de evaluciones_

2022-01-10 07:36 UTC, juan-cortizas-ponte commented
Buenos días @AngelFQC , ya estoy de vuelta, reviso y ejecuto cambios

2022-01-14 08:46 UTC, juan-cortizas-ponte commented
@AngelFQC 

Modificado para permitir configurar el servicio de Outcomes de LTI 1 desde /plugin/ims_lti/admin.php (Administración -> Plugins -> IMS/LTI)

![imagen](https://user-images.githubusercontent.com/48205899/149475738-8fb74843-1bef-43d3-96e7-8eb9eb8222c3.png)

El comportamiento es similar al de “Configuración del curso -> IMS/LTI / Configurar herramienta externa -> Permitir calificar en la herramienta de evaluaciones”, es decir, si no hay categoría del gradebook para el curso, el icono para generar la evaluación no aparece.

Obviamente también se modifica el proceso de generación de la evaluación para que se genere correctamente en el caso de un curso de sesión.

2022-01-18 11:53 UTC, juan-cortizas-ponte commented
@AngelFQC ¿está correcto ahora?

2022-01-21 20:21 UTC, merged