Upload - Add input file with progress with plugin bigupload - refs BT#19380
chamilo/chamilo-lms pull request #4174
Opened 2022-02-17 12:20 UTC by christianbeeznest

2022-02-17 17:26 UTC, AngelFQC requested changes
Remove `main/inc/lib/javascript/bigupload/example.html`
Remove `main/inc/lib/javascript/bigupload/js/jquery1.8.2.min.js`. Ya se usa jquery 2.2.4 en todo Chamilo

2022-02-18 22:22 UTC, AngelFQC approved these changes

2022-02-18 23:13 UTC, AngelFQC requested changes

2022-02-19 23:42 UTC, christianbeeznest commented
Gracias @AngelFQC , puedes agregar estas variables en el DLTT porfa ?

$FileUploadad = "File uploaded.";
$ThereWasAnErrorUploadingTheFile = "There was an error uploading the file";
$FileIsTooLarge = "File is too large.";
$UnableToDeleteTempFile = "Unable to delete temporary file.";

Gracias.

2022-03-11 09:17 UTC, merged

2022-04-04 15:52 UTC, christianbeeznest commented
> 

Hi fabiowoj ,

Pleate check all commits and run composer dumpautoload , it should add the new class BigUploadResponse in the autoload.

Thanks for confirmation.