Course : Add introduction content for main course and session - refs BT#19231
chamilo/chamilo-lms pull request #4234
Opened 2022-04-03 03:36 UTC by christianbeeznest

2022-05-18 12:49 UTC, ywarnier commented
@christianbeeznest This fixes the appearance of the edition box, but if I edit the introduction in the session course, when I return to the session-course homepage, I still see the base-course introduction (that is wrong, it should be the session-course introduction I just saved). When I refresh, it updates to the session-course introduction (which is correct).

2022-05-18 19:08 UTC, christianbeeznest commented
Hi @ywarnier , I just sent a commit with a fix, please run *yarn run encore dev* and clean cache (remove var/cache/*) to see the changes.

Thanks for confirmation.

2022-07-11 23:09 UTC, AngelFQC requested changes

2022-07-11 23:09 UTC, AngelFQC commented on src/CoreBundle/Controller/CourseController.php
> +        $session = api_get_session_entity();
Dentro de los controllers es mejor usar el session handle de Symfony y no usar api_get_session_entity

2022-07-11 23:09 UTC, AngelFQC commented on src/CoreBundle/Controller/CourseController.php
> +        $em = Database::getManager();
Usar la inyección de dependencias con EntityManagerInterface y no usar la clase Database

2022-07-11 23:09 UTC, AngelFQC commented on src/CoreBundle/Controller/CourseController.php
> +        return new Response(
Mejor usar `return new JsonResponse` o `return JsonResponse::fromJsonString`

2022-07-11 23:09 UTC, AngelFQC commented on src/CoreBundle/Controller/CourseController.php
> +        $em = Database::getManager();
Lo mismo con Database. No mezclar código legacy

2022-07-11 23:09 UTC, AngelFQC commented on src/CoreBundle/Controller/CourseController.php
> +        $session = api_get_session_entity($sid);
Lo mismo con api_get_session_entity. No mezclar código legacy

2022-07-11 23:09 UTC, AngelFQC commented on src/CoreBundle/Controller/CourseController.php
> +        return new Response(
Lo mismo para JsonResponse

2023-01-10 01:57 UTC, ywarnier commented
@christianbeeznest falta actualizar este y atender las observaciones de Angel (y una mía que quedó arriba)

2023-01-11 17:17 UTC, christianbeeznest commented on assets/vue/views/course/Home.vue
> +      });
La condicion esta dentro del controlador en el metodo getToolIntro .

2023-01-11 17:53 UTC, christianbeeznest commented on src/CoreBundle/Controller/CourseController.php
> +        $em = Database::getManager();
Corregido en el commit https://github.com/chamilo/chamilo-lms/pull/4234/commits/bf5ff0b8e654a6107c9a763493253bd24b1f21fc

2023-01-11 17:53 UTC, christianbeeznest commented on src/CoreBundle/Controller/CourseController.php
> +        return new Response(
Corregido en el commit https://github.com/chamilo/chamilo-lms/pull/4234/commits/bf5ff0b8e654a6107c9a763493253bd24b1f21fc

2023-01-11 17:53 UTC, christianbeeznest commented on src/CoreBundle/Controller/CourseController.php
> +        $em = Database::getManager();
Corregido en el commit https://github.com/chamilo/chamilo-lms/pull/4234/commits/bf5ff0b8e654a6107c9a763493253bd24b1f21fc

2023-01-11 17:54 UTC, christianbeeznest commented on src/CoreBundle/Controller/CourseController.php
> +        $session = api_get_session_entity();
Corregido.

2023-01-11 17:55 UTC, christianbeeznest commented
Corregido observaciones en el commit https://github.com/chamilo/chamilo-lms/pull/4234/commits/bf5ff0b8e654a6107c9a763493253bd24b1f21fc

2023-01-24 11:28 UTC, ywarnier commented
Sigo viendo conflictos para el merge, que no tengo idea de como resolver :smile:

2023-02-01 23:13 UTC, ywarnier commented
@christianbeeznest al final hacemos otro PR con esto, no? Ya se hizo o está pendiente?

2023-02-01 23:31 UTC, christianbeeznest commented
hola @ywarnier yo creo que creare otro PR con el master actualizado, veo que hay muchos cambios en ese archivo de esa version. Gracias.

2023-10-15 18:12 UTC, closed without merging