[BUG] Tracking fails for SCORM LPs on IExplorer
chamilo/chamilo-lms pull request #4245
Opened 2022-04-13 14:50 UTC by juan-cortizas-ponte

Tracking for SCORM LPs is not working on IExplorer because the EMACScript version that supports IE has no support for default parameters, so when the [method savedata(item_id, forceIframeSave) from main/lp/scorm_api.php](https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/lp/scorm_api.php#L877) is invoked the forceIframeSave = 0 is interpreted by the IE engine as a wrong syntax.

![imagen](https://user-images.githubusercontent.com/48205899/163206855-b3010bf0-8936-4b61-8593-ae09facf94cf.png)

We could fix it checking inside the method if the forceIframeSave has a value. If it has no value we could set it as zero.

![imagen](https://user-images.githubusercontent.com/48205899/163207188-74498195-47d7-4d4b-95f4-305468816c43.png)

![imagen](https://user-images.githubusercontent.com/48205899/163208006-2bdac467-3272-4532-b62a-523fd5e4dc96.png)

2022-04-13 15:07 UTC, AngelFQC requested changes

2022-04-13 15:38 UTC, juan-cortizas-ponte commented
@AngelFQC  refactorizado y probado, gracias!

2022-04-18 14:15 UTC, juan-cortizas-ponte commented on main/lp/scorm_api.php
> +    if (!forceIframeSave) {
Aplicados los cambios sugeridos!

2022-04-22 21:01 UTC, AngelFQC commented
Commits aplicados por cherry-picks en 1.11.x

76f80ab0ee2aac3f87d259833190521b864307b9
 3bd6b6e29cacbc91127b29ccb116caaa615ce65e

2022-04-22 21:01 UTC, closed without merging