Session List: Courses report export - refs BT#19878
chamilo/chamilo-lms pull request #4259
Opened 2022-04-25 12:27 UTC by lautarobeeznest

I used the variable "$Export2ZIP" because I thought it was the most convenient for the button.

2022-05-03 12:07 UTC, ywarnier requested changes

2022-05-03 12:07 UTC, ywarnier commented on main/session/session_list.php
> +        foreach ($sessionList as $session_id) {
Use `$sessionItemId`, then define `$session_id = $sessionItemId;` right before the call to `get_user_data()` (which uses `$session_id` as a global variable)

2022-05-04 07:37 UTC, NicoDucou commented
At a functional level it works fine, so once the code revision is good it can be merge for me.

2022-05-05 13:44 UTC, ywarnier approved these changes

2022-05-05 13:44 UTC, merged