Track Login - Add log of connection attempts - refs CT#3810
chamilo/chamilo-lms pull request #4344
Opened 2022-07-08 04:36 UTC by christianbeeznest

2022-07-13 18:51 UTC, AngelFQC requested changes
La request a la ruta /login_json debería bastar para registrar el login correcto o fallido.
Porque este método es llamado después que Symfony detecta un intento de inicio de sesión

https://symfony.com/doc/5.4/security.html#json-login

2022-07-13 18:51 UTC, AngelFQC commented on assets/vue/components/Login.vue
> +    });
Si el login ya falló no se debería reenviar la contraseña

2022-07-13 18:51 UTC, AngelFQC commented on src/CoreBundle/Controller/SecurityController.php
> +            ->setUsername($params['username'])
No es necesario obtener el username del contenido de la request, porque más abajo se obtiene el usuario que inició sesión satisfactoriamente ($user = $this->getUser()).

2022-07-13 18:51 UTC, AngelFQC commented on src/CoreBundle/Controller/SecurityController.php
> +    public function loginFailed(Request $request): JsonResponse
El trackELoginRecord con success = false se puede registrar en el mismo loginJson dentro de la primera condición (`if (!$this->isGranted('IS_AUTHENTICATED_FULLY'))`), lo que ahorraría una request más cuando el login falla

2022-07-14 05:30 UTC, christianbeeznest commented
I close this PR to avoid conflicting

2022-07-14 05:30 UTC, closed without merging