Text2Speech Plugin #4622
chamilo/chamilo-lms pull request #4623
Opened 2023-02-28 16:15 UTC by FraGoTe

2023-02-28 17:45 UTC, AngelFQC commented
Remove the .DS_Store files

2023-02-28 18:57 UTC, AngelFQC requested changes

2023-02-28 18:57 UTC, AngelFQC commented on plugin/ai_helper/tool/learnpath.php
> +$isTextToSpeechEnabled = $text2speechPlugin->get_name('tool_enable') && $text2speechPlugin->get_name('tool_lp_enable');
$text2speechPlugin->get('NOMBRE_DE_SETTING');

2023-02-28 23:41 UTC, FraGoTe commented
@AngelFQC acabo de hacer los cambios que solicitaste, gracias por el code review!

2023-03-01 11:59 UTC, ywarnier commented
Ya entendí, haces el proceso de TTS al momento de la creación del learning path por el plugin AI Helper. Está bien, pero sería mucho mejor si pudieras ofrecer la posibilidad a alguien de hacerlo luego de la generación. En particular en lp_controller.php?action=add_audio, que es una página dedicada al audio y tiene varias secciones de fuentes distintas.

El problema de hacerlo únicamente al momento de la generación de la lección es que todavía consideramos que AI Helper solo hará una pre-generación que tiene que ser validada/corregida por el profesor. Por eso, generar el audio sin posibilidad de volver a hacer el proceso es un problema, porque probablemente 50% del tiempo el profesor va a cambiar ligeramente el texto antes de validar (y nos quedaríamos con un audio que no corresponde).

Puedes encontrar el formulario normal de add_audio aquí: main/lp/lp_add_audio.php y introducir un check sobre la existencia y activación del plugin text2speech antes de mostrar una sección más para la generación de audio.

Observo que no veo de ningún lado una elección de idiomas. Supongo que por ahora quedará así (entiendo que se necesita otro modelo y probablemente otra instancia de servidor TTS para generar el audio en otro idioma), pero hay oportunidades de mejora por este lado (por ejemplo permitiendo la configuración de distintas URLs y API keys según un idioma).

2023-03-01 12:05 UTC, ywarnier commented
Sugeencia de README.md (que cambiará si agregas el formulario):
```
Text2Speech
=

This plugin adds the possibility (once setup with 3rd party account) to add 
speech to learning paths by converting text in the learning paths to audio 
files attached to each learning path item.

This plugin requires the *installation and configuration* of the TTS software
and data from Mozilla, which might be deterring to most users (sorry about 
that). Please refer to https://github.com/mozilla/TTS/wiki on how to download,
install and configure your own TTS server.

It also requires the "AI Helper" plugin to be installed, enabled and properly
configured, as it connects to the learning path auto-generation feature to add
audio to it.

Once your TTS server is available, get a URL to connect to it, install and 
enable the plugin, give it an API key (if any), a host (could be localhost)
and enable the plugin in the learning paths, then create a new learning 
path using the AI Helper plugin in the learning path tool. You should now 
get additional speech for every document in your learning path. 
```

2023-03-01 13:29 UTC, ywarnier commented
Other suggestion: Add this to lang/english.php:
```
$strings['api_name'] = 'API';
$strings['api_key'] = 'API key';
$strings['url'] = 'URL of your Text2Speech server';
$strings['tool_lp_enable'] = 'Enable into the learning path';
```
spanish.php
```
$strings['api_name'] = 'API';
$strings['api_key'] = 'Clave API';
$strings['url'] = 'URL del servidor Text2Speech';
$strings['tool_lp_enable'] = 'Activar en las lecciones';
```
french.php
```
$strings['api_name'] = 'API';
$strings['api_key'] = 'Clef API';
$strings['url'] = 'URL du serveur de Text2Speech';
$strings['tool_lp_enable'] = 'Activer dans les parcours';
```

2023-03-01 18:29 UTC, AngelFQC commented on plugin/text2speech/src/mozillatts/MozillaTTS.php
> +        $client->get($this->url.'?api_key='.urlencode($this->apiKey).
El api_key es necesario? Cómo lo genero? En mi TTS que tengo no pide api_key y me genera los audios por el api solo con el texto
:thinking:

2023-03-02 15:14 UTC, FraGoTe commented on plugin/text2speech/src/mozillatts/MozillaTTS.php
> +        $client->get($this->url.'?api_key='.urlencode($this->apiKey).
exacto en este momento no es necesario pero lo dejo abierto por si se necesita en algún otro servicio.

2023-03-02 15:20 UTC, FraGoTe commented
> Ya entendí, haces el proceso de TTS al momento de la creación del learning path por el plugin AI Helper. Está bien, pero sería mucho mejor si pudieras ofrecer la posibilidad a alguien de hacerlo luego de la generación. En particular en lp_controller.php?action=add_audio, que es una página dedicada al audio y tiene varias secciones de fuentes distintas.
> 
> El problema de hacerlo únicamente al momento de la generación de la lección es que todavía consideramos que AI Helper solo hará una pre-generación que tiene que ser validada/corregida por el profesor. Por eso, generar el audio sin posibilidad de volver a hacer el proceso es un problema, porque probablemente 50% del tiempo el profesor va a cambiar ligeramente el texto antes de validar (y nos quedaríamos con un audio que no corresponde).
> 
> Puedes encontrar el formulario normal de add_audio aquí: main/lp/lp_add_audio.php y introducir un check sobre la existencia y activación del plugin text2speech antes de mostrar una sección más para la generación de audio.
> 
> Observo que no veo de ningún lado una elección de idiomas. Supongo que por ahora quedará así (entiendo que se necesita otro modelo y probablemente otra instancia de servidor TTS para generar el audio en otro idioma), pero hay oportunidades de mejora por este lado (por ejemplo permitiendo la configuración de distintas URLs y API keys según un idioma).

Si por lo último que comentas en el caso de mozilla TTS se despliega un modelo por cada idioma, se podría poner algo delante para ir al idioma que se necesite por este momento podemos dejarlo así y ya despues agregar el soporte para multiidioma lo cual creo que es va a tener que ser algo manual, ya que por ejemplo en el LP tendrían que seleccionar el idioma en el que quieren el audio.

2023-03-02 20:47 UTC, ywarnier commented
> Si por lo último que comentas en el caso de mozilla TTS se despliega un modelo por cada idioma, se podría poner algo delante para ir al idioma que se necesite por este momento podemos dejarlo así y ya despues agregar el soporte para multiidioma lo cual creo que es va a tener que ser algo manual, ya que por ejemplo en el LP tendrían que seleccionar el idioma en el que quieren el audio.

Es más fácil que esto : podemos usar el idioma del curso en el cual el LP está ubicado. Esta parte no me preocupa. Es más saber si hay un servidor TTS que soporte varios modelos a la vez o si se van a tener que lanzar varios servidores TTS, uno para cada modelo/idioma. Pero bueno, iremos descubriendo esto con el tiempo

2023-03-11 15:54 UTC, ywarnier commented
Closing this PR. See notes in #4629 for explicit reasons.

2023-03-11 15:54 UTC, closed without merging

2023-03-11 15:54 UTC, ywarnier commented
This doesn't diminish our gratitude for your contribution to Chamilo (as the PR based on yours will remain open for a possible later integration)