Course: Add text format info to enable alternate formatting - refs #4305
chamilo/chamilo-lms pull request #4633
Opened 2023-03-06 20:32 UTC by christianbeeznest

2023-03-14 16:26 UTC, AngelFQC requested changes

2023-03-14 16:26 UTC, AngelFQC commented on src/CoreBundle/Entity/ResourceFormat.php
> +    {
```
/**
* @return Collection<int, ResourceNode>
*/
public function getResourceNodes(): Collection
```

2023-03-14 16:26 UTC, AngelFQC commented on src/CoreBundle/Entity/ResourceFormat.php
> +    public function setResourceNodes($resourceNodes): self
```
public function setResourceNodes(Collection $resourceNodes)
```

2023-06-07 16:50 UTC, christianbeeznest commented
I close this PR to create one with the last changes in master

2023-06-07 16:50 UTC, closed without merging