Admin: Fix error when legal terms is created - refs BT#20846
chamilo/chamilo-lms pull request #4859
Opened 2023-08-29 19:03 UTC by christianbeeznest

2023-08-29 23:52 UTC, AngelFQC requested changes

2023-08-29 23:52 UTC, AngelFQC commented on public/main/inc/lib/legal.lib.php
> +        if ((isset($last['content']) && $last['content'] != $content) || !empty($changeList) || empty($last)) {
En la línea 33 se valida si $last es false, pero debería validarse si es un array vacío para no estar validando en cada condicional

33: `if (false === $last) {`

2023-08-30 12:09 UTC, christianbeeznest commented on public/main/inc/lib/legal.lib.php
> +        if ((isset($last['content']) && $last['content'] != $content) || !empty($changeList) || empty($last)) {
Hola @AngelFQC , eso es la parte del legal que no entiendo su logica y funcionamiento, en la linea 33 si le valido que es vacio el array ya no continua la funcion y por lo tanto no se crearia lo terminos para ese idioma si aun no existe, por eso en la linea 64 agrego que si es empty va entrar a esa condicional donde se crearia ahi el termino. La verdad no se si esta bien esa logica antigua del legal porque con eso esta forzando a que el termino de ese idioma exista y que pasa si no hay, nunca se va crear para ese idioma, me ayudas a entender su funcionamiento porfa para ver si cambio toda la funcion ?

Gracias.

2023-09-05 06:00 UTC, christianbeeznest commented
Cierro este PR por conflictos de archivos, creado otro con los cambios actuales.

2023-09-05 06:00 UTC, closed without merging