Skill: Add messages after assigning user badge - refs BT#20912
chamilo/chamilo-lms pull request #4869
Opened 2023-09-06 22:49 UTC by christianbeeznest

2023-09-07 14:25 UTC, AngelFQC requested changes

2023-09-07 14:25 UTC, AngelFQC commented on public/main/inc/lib/SkillModel.php
> +
Esto sería mejor, pasarlo a un EntityListener de SkillRelUser. Para que cuando se haga el persist se envíe el mensaje

2023-09-07 14:25 UTC, AngelFQC commented on public/main/skills/assign.php
> -
Los mensajes con addFlash, ahora ya se muestran correctamente

2023-09-10 11:50 UTC, christianbeeznest commented
Cierro este PR para evitar conflictos con master.

2023-09-10 11:50 UTC, closed without merging