[C2] Delete some components that are not used
chamilo/chamilo-lms pull request #5385
Opened 2024-04-17 10:21 UTC by daniboygg

This will remove components that are not in use in Vue application. This will delete some unneeded vuex dependencies.

#5377

2024-04-23 09:14 UTC, ywarnier commented
I'm not able to review this one, in particular because of the assets/vue/router/course.js removal. I think *maybe* the corresponding views are a work in progress to be used later. @AngelFQC if these are not works in progress, can we remove them and implement them correctly later on, or should we keep them there to hold the place for the file to be used later?

2024-04-23 15:54 UTC, AngelFQC requested changes

2024-04-23 15:54 UTC, AngelFQC commented on assets/vue/router/course.js
> -    },
CourseCreate is currently in use

2024-04-23 15:54 UTC, AngelFQC commented on assets/vue/views/course/Create.vue
This page is used to allow teachers to create their courses  (from the orange button on the /courses page)

2024-04-24 12:19 UTC, daniboygg commented
I reverted the changes. So, do we need the components CourseList, CourseUpdate and CourseShow. All of them are using vuex, but when I visit the route I see nothing. 
I think we should fix these components before remove vuex, otherwise it will be difficult to ensure the behavior is consistent with the old one.

2024-04-24 12:20 UTC, daniboygg commented on assets/vue/views/course/Create.vue
> +const violations = ref(null)
The reference violations is used in the component CourseForm but this component has no property errors...
```html
<CourseForm
      ref="createForm"
      :errors="violations"
      :values="item"
      @submit="submitCourse"
    />
```

2024-07-03 19:04 UTC, ywarnier commented
Tested. I don't see anything missing, feature-wise, by testing it with this PR. Will include soon in master.

2024-07-04 21:57 UTC, merged