Internal: Filter courses by access URL if multiple URLs enabled
chamilo/chamilo-lms pull request #5682
Opened 2024-07-19 18:58 UTC by christianbeeznest

2024-07-19 19:03 UTC, AngelFQC requested changes

2024-07-19 19:03 UTC, AngelFQC commented on src/CoreBundle/ServiceHelper/AccessUrlHelper.php
> +    }
Actualiza tu rama, ahora hay un método isMultiple que ya hace esto :)

2024-07-19 19:03 UTC, AngelFQC commented on src/CoreBundle/DataProvider/Extension/CourseExtension.php
> +        if ($this->accessUrlHelper->hasMultipleAccessUrls()) {
```diff
if ($this->accessUrlHelper->isMultiple()) {
```

2024-07-26 23:39 UTC, christianbeeznest commented
I close this ticket, it will be created other with last changes.

2024-07-26 23:39 UTC, closed without merging